/*
 * DFS all possible states and store in table to check in O(1)
 */
#include <vector>
#include <unordered_set>
#include <string>
#include "catch.hpp"
using std::vector;
using std::string;
using std::unordered_set;

static unordered_set< string> states{
"         ","        X","       OX","       X ","       XO","      O X","      OX ","      OXX",
"      X  ","      X O","      XO ","      XOX","      XXO","     O  X","     O X ","     O XX",
"     OOXX","     OX  ","     OX X","     OXOX","     OXX ","     OXXO","     X   ","     X  O",
"     X O ","     X OX","     X XO","     XO  ","     XO X","     XOOX","     XOX ","     XOXO",
"     XX O","     XXO ","     XXOO","    O   X","    O  X ","    O  XX","    O OXX","    O X  ",
"    O X X","    O XOX","    O XX ","    O XXO","    OO XX","    OOX X","    OOXX ","    OOXXX",
"    OX   ","    OX  X","    OX OX","    OX X ","    OX XO","    OXO X","    OXOX ","    OXOXX",
"    OXX  ","    OXX O","    OXXO ","    OXXOX","    OXXXO","    X    ","    X   O","    X  O ",
"    X  OX","    X  XO","    X O  ","    X O X","    X OOX","    X OX ","    X OXO","    X X O",
"    X XO ","    X XOO","    XO   ","    XO  X","    XO OX","    XO X ","    XO XO","    XOO X",
"    XOOX ","    XOOXX","    XOX  ","    XOX O","    XOXO ","    XOXOX","    XOXXO","    XX  O",
"    XX O ","    XX OO","    XXO  ","    XXO O","    XXOO ","    XXOOX","    XXOXO","    XXXOO",
"   O    X","   O   X ","   O   XX","   O  OXX","   O  X  ","   O  X X","   O  XOX","   O  XX ",
"   O  XXO","   O O XX","   O OX X","   O OXX ","   O OXXX","   O X   ","   O X  X","   O X OX",
"   O X X ","   O X XO","   O XO X","   O XOX ","   O XOXX","   O XX  ","   O XX O","   O XXO ",
"   O XXOX","   O XXXO","   OO  XX","   OO X X","   OO XX ","   OO XXX","   OOX  X","   OOX X ",
"   OOX XX","   OOXOXX","   OOXX  ","   OOXX X","   OOXXOX","   OOXXX ","   OOXXXO","   OX    ",
"   OX   X","   OX  OX","   OX  X ","   OX  XO","   OX O X","   OX OX ","   OX OXX","   OX X  ",
"   OX X O","   OX XO ","   OX XOX","   OX XXO","   OXO  X","   OXO X ","   OXO XX","   OXOOXX",
"   OXOX  ","   OXOX X","   OXOXOX","   OXOXX ","   OXOXXO","   OXX   ","   OXX  O","   OXX O ",
"   OXX OX","   OXX XO","   OXXO  ","   OXXO X","   OXXOOX","   OXXOX ","   OXXOXO","   OXXX O",
"   OXXXO ","   OXXXOO","   X     ","   X    O","   X   O ","   X   OX","   X   XO","   X  O  ",
"   X  O X","   X  OOX","   X  OX ","   X  OXO","   X  X O","   X  XO ","   X  XOO","   X O   ",
"   X O  X","   X O OX","   X O X ","   X O XO","   X OO X","   X OOX ","   X OOXX","   X OX  ",
"   X OX O","   X OXO ","   X OXOX","   X OXXO","   X X  O","   X X O ","   X X OO","   X XO  ",
"   X XO O","   X XOO ","   X XOOX","   X XOXO","   X XXOO","   XO    ","   XO   X","   XO  OX",
"   XO  X ","   XO  XO","   XO O X","   XO OX ","   XO OXX","   XO X  ","   XO X O","   XO XO ",
"   XO XOX","   XO XXO","   XOO  X","   XOO X ","   XOO XX","   XOOOXX","   XOOX  ","   XOOX X",
"   XOOXOX","   XOOXX ","   XOOXXO","   XOX   ","   XOX  O","   XOX O ","   XOX OX","   XOX XO",
"   XOXO  ","   XOXO X","   XOXOOX","   XOXOX ","   XOXOXO","   XOXX O","   XOXXO ","   XOXXOO",
"   XX   O","   XX  O ","   XX  OO","   XX O  ","   XX O O","   XX OO ","   XX OOX","   XX OXO",
"   XX XOO","   XXO   ","   XXO  O","   XXO O ","   XXO OX","   XXO XO","   XXOO  ","   XXOO X",
"   XXOOOX","   XXOOX ","   XXOOXO","   XXOX O","   XXOXO ","   XXOXOO","   XXX OO","   XXXO O",
"   XXXOO ","  O     X","  O    X ","  O    XX","  O   OXX","  O   X  ","  O   X X","  O   XOX",
"  O   XX ","  O   XXO","  O  O XX","  O  OX X","  O  OXX ","  O  OXXX","  O  X   ","  O  X  X",
"  O  X OX","  O  X X ","  O  X XO","  O  XO X","  O  XOX ","  O  XOXX","  O  XX  ","  O  XX O",
"  O  XXO ","  O  XXOX","  O  XXXO","  O O  XX","  O O X X","  O O XX ","  O O XXX","  O OX  X",
"  O OX X ","  O OX XX","  O OXOXX","  O OXX  ","  O OXX X","  O OXXOX","  O OXXX ","  O OXXXO",
"  O X    ","  O X   X","  O X  OX","  O X  X ","  O X  XO","  O X O X","  O X OX ","  O X OXX",
"  O X X  ","  O X X O","  O X XO ","  O X XOX","  O X XXO","  O XO  X","  O XO X ","  O XO XX",
"  O XOOXX","  O XOX  ","  O XOX X","  O XOXOX","  O XOXX ","  O XOXXO","  O XX   ","  O XX  O",
"  O XX O ","  O XX OX","  O XX XO","  O XXO  ","  O XXO X","  O XXOOX","  O XXOX ","  O XXOXO",
"  O XXX O","  O XXXO ","  O XXXOO","  OO   XX","  OO  X X","  OO  XX ","  OO  XXX","  OO X  X",
"  OO X X ","  OO X XX","  OO XOXX","  OO XX  ","  OO XX X","  OO XXOX","  OO XXX ","  OO XXXO",
"  OOOX XX","  OOOXX X","  OOOXXX ","  OOOXXXX","  OOX   X","  OOX  X ","  OOX  XX","  OOX OXX",
"  OOX X  ","  OOX X X","  OOX XOX","  OOX XX ","  OOX XXO","  OOXO XX","  OOXOX X","  OOXOXX ",
"  OOXOXXX","  OOXX   ","  OOXX  X","  OOXX OX","  OOXX X ","  OOXX XO","  OOXXO X","  OOXXOX ",
"  OOXXOXX","  OOXXX  ","  OOXXX O","  OOXXXO ","  OOXXXOX","  OOXXXXO","  OX     ","  OX    X",
"  OX   OX","  OX   X ","  OX   XO","  OX  O X","  OX  OX ","  OX  OXX","  OX  X  ","  OX  X O",
"  OX  XO ","  OX  XOX","  OX  XXO","  OX O  X","  OX O X ","  OX O XX","  OX OOXX","  OX OX  ",
"  OX OX X","  OX OXOX","  OX OXX ","  OX OXXO","  OX X   ","  OX X  O","  OX X O ","  OX X OX",
"  OX X XO","  OX XO  ","  OX XO X","  OX XOOX","  OX XOX ","  OX XOXO","  OX XX O","  OX XXO ",
"  OX XXOO","  OXO   X","  OXO  X ","  OXO  XX","  OXO OXX","  OXO X  ","  OXO X X","  OXO XOX",
"  OXO XX ","  OXO XXO","  OXOO XX","  OXOOX X","  OXOOXX ","  OXOOXXX","  OXOX   ","  OXOX  X",
"  OXOX OX","  OXOX X ","  OXOX XO","  OXOXO X","  OXOXOX ","  OXOXX  ","  OXOXX O","  OXOXXO ",
"  OXOXXOX","  OXOXXXO","  OXX    ","  OXX   O","  OXX  O ","  OXX  OX","  OXX  XO","  OXX O  ",
"  OXX O X","  OXX OOX","  OXX OX ","  OXX OXO","  OXX X O","  OXX XO ","  OXX XOO","  OXXO   ",
"  OXXO  X","  OXXO OX","  OXXO X ","  OXXO XO","  OXXOO X","  OXXOOX ","  OXXOOXX","  OXXOX  ",
"  OXXOX O","  OXXOXO ","  OXXOXOX","  OXXX  O","  OXXX O ","  OXXXO  ","  OXXXOOX","  OXXXOXO",
"  OXXXXOO","  X      ","  X     O","  X    O ","  X    OX","  X    XO","  X   O  ","  X   O X",
"  X   OOX","  X   OX ","  X   OXO","  X   X O","  X   XO ","  X   XOO","  X  O   ","  X  O  X",
"  X  O OX","  X  O X ","  X  O XO","  X  OO X","  X  OOX ","  X  OOXX","  X  OX  ","  X  OX O",
"  X  OXO ","  X  OXOX","  X  OXXO","  X  X  O","  X  X O ","  X  X OO","  X  XO  ","  X  XO O",
"  X  XOO ","  X  XOOX","  X  XOXO","  X  XXOO","  X O    ","  X O   X","  X O  OX","  X O  X ",
"  X O  XO","  X O O X","  X O OX ","  X O OXX","  X O X  ","  X O X O","  X O XO ","  X O XOX",
"  X O XXO","  X OO  X","  X OO X ","  X OO XX","  X OOOXX","  X OOX  ","  X OOX X","  X OOXOX",
"  X OOXX ","  X OOXXO","  X OX   ","  X OX  O","  X OX O ","  X OX OX","  X OX XO","  X OXO  ",
"  X OXO X","  X OXOX ","  X OXOXO","  X OXX O","  X OXXO ","  X OXXOO","  X X   O","  X X  O ",
"  X X  OO","  X X O  ","  X X O O","  X X OO ","  X X OOX","  X X OXO","  X X XOO","  X XO   ",
"  X XO  O","  X XO O ","  X XO OX","  X XO XO","  X XOO  ","  X XOO X","  X XOOOX","  X XOOX ",
"  X XOOXO","  X XOX O","  X XOXO ","  X XX OO","  X XXO O","  X XXOO ","  X XXOOO","  XO     ",
"  XO    X","  XO   OX","  XO   X ","  XO   XO","  XO  O X","  XO  OX ","  XO  OXX","  XO  X  ",
"  XO  X O","  XO  XO ","  XO  XOX","  XO  XXO","  XO O  X","  XO O X ","  XO O XX","  XO OOXX",
"  XO OX  ","  XO OX X","  XO OXOX","  XO OXX ","  XO OXXO","  XO X   ","  XO X  O","  XO X O ",
"  XO X OX","  XO X XO","  XO XO  ","  XO XO X","  XO XOX ","  XO XOXO","  XO XX O","  XO XXO ",
"  XO XXOO","  XOO   X","  XOO  X ","  XOO  XX","  XOO OXX","  XOO X  ","  XOO X X","  XOO XOX",
"  XOO XX ","  XOO XXO","  XOOO XX","  XOOOX X","  XOOOXX ","  XOOX   ","  XOOX  X","  XOOX X ",
"  XOOX XO","  XOOXOX ","  XOOXOXX","  XOOXX  ","  XOOXX O","  XOOXXO ","  XOOXXOX","  XOOXXXO",
"  XOX    ","  XOX   O","  XOX  O ","  XOX  OX","  XOX  XO","  XOX O  ","  XOX O X","  XOX OOX",
"  XOX OX ","  XOX OXO","  XOX X O","  XOX XO ","  XOXO   ","  XOXO  X","  XOXO OX","  XOXO X ",
"  XOXO XO","  XOXOO X","  XOXOOX ","  XOXOOXX","  XOXOX  ","  XOXOXOX","  XOXOXXO","  XOXX  O",
"  XOXX O ","  XOXX OO","  XOXXO  ","  XOXXO O","  XOXXOO ","  XOXXOOX","  XOXXOXO","  XOXXXOO",
"  XX    O","  XX   O ","  XX   OO","  XX  O  ","  XX  O O","  XX  OO ","  XX  OOX","  XX  OXO",
"  XX  XOO","  XX O   ","  XX O  O","  XX O O ","  XX O OX","  XX O XO","  XX OO  ","  XX OO X",
"  XX OOOX","  XX OOX ","  XX OOXO","  XX OX O","  XX OXO ","  XX OXOO","  XX X OO","  XX XO O",
"  XX XOO ","  XX XOOO","  XXO    ","  XXO   O","  XXO  O ","  XXO  OX","  XXO  XO","  XXO O  ",
"  XXO O X","  XXO OOX","  XXO OX ","  XXO OXO","  XXO X O","  XXO XO ","  XXO XOO","  XXOO   ",
"  XXOO  X","  XXOO OX","  XXOO X ","  XXOO XO","  XXOOO X","  XXOOOX ","  XXOOOXX","  XXOOX  ",
"  XXOOX O","  XXOOXO ","  XXOOXOX","  XXOOXXO","  XXOX  O","  XXOX O ","  XXOX OO","  XXOXO  ",
"  XXOXO O","  XXOXOO ","  XXOXOOX","  XXOXOXO","  XXOXXOO","  XXX  OO","  XXX O O","  XXX OO ",
"  XXX OOO","  XXXO  O","  XXXO O ","  XXXO OO","  XXXOO  ","  XXXOO O","  XXXOOO ","  XXXOOOX",
"  XXXOOXO","  XXXOXOO"," O      X"," O     X "," O     XX"," O    OXX"," O    X  "," O    X X",
" O    XOX"," O    XX "," O    XXO"," O   O XX"," O   OX X"," O   OXX "," O   OXXX"," O   X   ",
" O   X  X"," O   X OX"," O   X X "," O   X XO"," O   XO X"," O   XOX "," O   XOXX"," O   XX  ",
" O   XX O"," O   XXO "," O   XXOX"," O   XXXO"," O  O  XX"," O  O X X"," O  O XX "," O  O XXX",
" O  OX  X"," O  OX X "," O  OX XX"," O  OXOXX"," O  OXX  "," O  OXX X"," O  OXXOX"," O  OXXX ",
" O  OXXXO"," O  X    "," O  X   X"," O  X  OX"," O  X  X "," O  X  XO"," O  X O X"," O  X OX ",
" O  X OXX"," O  X X  "," O  X X O"," O  X XO "," O  X XOX"," O  X XXO"," O  XO  X"," O  XO X ",
" O  XO XX"," O  XOOXX"," O  XOX  "," O  XOX X"," O  XOXOX"," O  XOXX "," O  XOXXO"," O  XX   ",
" O  XX  O"," O  XX O "," O  XX OX"," O  XX XO"," O  XXO  "," O  XXO X"," O  XXOOX"," O  XXOX ",
" O  XXOXO"," O  XXX O"," O  XXXO "," O  XXXOO"," O O   XX"," O O  X X"," O O  XX "," O O  XXX",
" O O X  X"," O O X X "," O O X XX"," O O XOXX"," O O XX  "," O O XX X"," O O XXOX"," O O XXX ",
" O O XXXO"," O OOX XX"," O OOXX X"," O OOXXX "," O OOXXXX"," O OX   X"," O OX  X "," O OX  XX",
" O OX OXX"," O OX X  "," O OX X X"," O OX XOX"," O OX XX "," O OX XXO"," O OXO XX"," O OXOX X",
" O OXOXX "," O OXOXXX"," O OXX   "," O OXX  X"," O OXX OX"," O OXX X "," O OXX XO"," O OXXO X",
" O OXXOX "," O OXXOXX"," O OXXX  "," O OXXX O"," O OXXXO "," O OXXXOX"," O OXXXXO"," O X     ",
" O X    X"," O X   OX"," O X   X "," O X   XO"," O X  O X"," O X  OX "," O X  OXX"," O X  X  ",
" O X  X O"," O X  XO "," O X  XOX"," O X  XXO"," O X O  X"," O X O X "," O X O XX"," O X OOXX",
" O X OX  "," O X OX X"," O X OXOX"," O X OXX "," O X OXXO"," O X X   "," O X X  O"," O X X O ",
" O X X OX"," O X X XO"," O X XO  "," O X XO X"," O X XOOX"," O X XOX "," O X XOXO"," O X XX O",
" O X XXO "," O X XXOO"," O XO   X"," O XO  X "," O XO  XX"," O XO OXX"," O XO X  "," O XO X X",
" O XO XOX"," O XO XX "," O XO XXO"," O XOO XX"," O XOOX X"," O XOOXX "," O XOOXXX"," O XOX   ",
" O XOX  X"," O XOX OX"," O XOX X "," O XOX XO"," O XOXO X"," O XOXOX "," O XOXOXX"," O XOXX  ",
" O XOXX O"," O XOXXO "," O XOXXXO"," O XX    "," O XX   O"," O XX  O "," O XX  OX"," O XX  XO",
" O XX O  "," O XX O X"," O XX OOX"," O XX OX "," O XX OXO"," O XX X O"," O XX XO "," O XX XOO",
" O XXO   "," O XXO  X"," O XXO OX"," O XXO X "," O XXO XO"," O XXOO X"," O XXOOX "," O XXOOXX",
" O XXOX  "," O XXOX O"," O XXOXO "," O XXOXOX"," O XXOXXO"," O XXX  O"," O XXX O "," O XXXO  ",
" O XXXOOX"," O XXXOXO"," O XXXXOO"," OO    XX"," OO   X X"," OO   XX "," OO   XXX"," OO  X  X",
" OO  X X "," OO  X XX"," OO  XOXX"," OO  XX  "," OO  XX X"," OO  XXOX"," OO  XXX "," OO  XXXO",
" OO OX XX"," OO OXX X"," OO OXXX "," OO OXXXX"," OO X   X"," OO X  X "," OO X  XX"," OO X OXX",
" OO X X  "," OO X X X"," OO X XOX"," OO X XX "," OO X XXO"," OO XO XX"," OO XOX X"," OO XOXX ",
" OO XOXXX"," OO XX   "," OO XX  X"," OO XX OX"," OO XX X "," OO XX XO"," OO XXO X"," OO XXOX ",
" OO XXOXX"," OO XXX  "," OO XXX O"," OO XXXO "," OO XXXOX"," OO XXXXO"," OOO X XX"," OOO XX X",
" OOO XXX "," OOO XXXX"," OOOX  XX"," OOOX X X"," OOOX XX "," OOOX XXX"," OOOXX  X"," OOOXX X ",
" OOOXX XX"," OOOXXOXX"," OOOXXX  "," OOOXXX X"," OOOXXXOX"," OOOXXXX "," OOOXXXXO"," OOX    X",
" OOX   X "," OOX   XX"," OOX  OXX"," OOX  X  "," OOX  X X"," OOX  XOX"," OOX  XX "," OOX  XXO",
" OOX O XX"," OOX OX X"," OOX OXX "," OOX OXXX"," OOX X   "," OOX X  X"," OOX X OX"," OOX X X ",
" OOX X XO"," OOX XO X"," OOX XOX "," OOX XOXX"," OOX XX  "," OOX XX O"," OOX XXO "," OOX XXOX",
" OOX XXXO"," OOXO  XX"," OOXO X X"," OOXO XX "," OOXO XXX"," OOXOX  X"," OOXOX X "," OOXOX XX",
" OOXOXOXX"," OOXOXX  "," OOXOXX X"," OOXOXXOX"," OOXOXXX "," OOXOXXXO"," OOXX    "," OOXX   X",
" OOXX  OX"," OOXX  X "," OOXX  XO"," OOXX O X"," OOXX OX "," OOXX OXX"," OOXX X  "," OOXX X O",
" OOXX XO "," OOXX XOX"," OOXX XXO"," OOXXO  X"," OOXXO X "," OOXXO XX"," OOXXOOXX"," OOXXOX  ",
" OOXXOX X"," OOXXOXOX"," OOXXOXX "," OOXXOXXO"," OOXXX   "," OOXXX OX"," OOXXX XO"," OOXXXO X",
" OOXXXOX "," OOXXXX O"," OOXXXXO "," OX      "," OX     X"," OX    OX"," OX    X "," OX    XO",
" OX   O X"," OX   OX "," OX   OXX"," OX   X  "," OX   X O"," OX   XO "," OX   XOX"," OX   XXO",
" OX  O  X"," OX  O X "," OX  O XX"," OX  OOXX"," OX  OX  "," OX  OX X"," OX  OXOX"," OX  OXX ",
" OX  OXXO"," OX  X   "," OX  X  O"," OX  X O "," OX  X OX"," OX  X XO"," OX  XO  "," OX  XO X",
" OX  XOX "," OX  XOXO"," OX  XX O"," OX  XXO "," OX  XXOO"," OX O   X"," OX O  X "," OX O  XX",
" OX O OXX"," OX O X  "," OX O X X"," OX O XOX"," OX O XX "," OX O XXO"," OX OO XX"," OX OOX X",
" OX OOXX "," OX OOXXX"," OX OX   "," OX OX  X"," OX OX X "," OX OX XO"," OX OXOX "," OX OXOXX",
" OX OXX  "," OX OXX O"," OX OXXO "," OX OXXXO"," OX X    "," OX X   O"," OX X  O "," OX X  OX",
" OX X  XO"," OX X O  "," OX X O X"," OX X OOX"," OX X OX "," OX X OXO"," OX X X O"," OX X XO ",
" OX XO   "," OX XO  X"," OX XO OX"," OX XO X "," OX XO XO"," OX XOO X"," OX XOOX "," OX XOOXX",
" OX XOX  "," OX XOXOX"," OX XOXXO"," OX XX  O"," OX XX O "," OX XX OO"," OX XXO  "," OX XXO O",
" OX XXOO "," OX XXOOX"," OX XXOXO"," OX XXXOO"," OXO    X"," OXO   X "," OXO   XX"," OXO  OXX",
" OXO  X  "," OXO  X X"," OXO  XOX"," OXO  XX "," OXO  XXO"," OXO O XX"," OXO OX X"," OXO OXX ",
" OXO OXXX"," OXO X   "," OXO X  X"," OXO X X "," OXO X XO"," OXO XOX "," OXO XOXX"," OXO XX  ",
" OXO XX O"," OXO XXO "," OXO XXOX"," OXO XXXO"," OXOO  XX"," OXOO X X"," OXOO XX "," OXOO XXX",
" OXOOX X "," OXOOX XX"," OXOOXX  "," OXOOXX X"," OXOOXXX "," OXOOXXXO"," OXOX    "," OXOX   X",
" OXOX  OX"," OXOX  X "," OXOX  XO"," OXOX O X"," OXOX OX "," OXOX OXX"," OXOX X  "," OXOX XOX",
" OXOX XXO"," OXOXO  X"," OXOXO X "," OXOXO XX"," OXOXOOXX"," OXOXOX X"," OXOXOXX "," OXOXX   ",
" OXOXX  O"," OXOXX O "," OXOXX OX"," OXOXX XO"," OXOXXO  "," OXOXXO X"," OXOXXOX "," OXOXXOXO",
" OXOXXX O"," OXOXXXO "," OXX     "," OXX    O"," OXX   O "," OXX   OX"," OXX   XO"," OXX  O  ",
" OXX  O X"," OXX  OOX"," OXX  OX "," OXX  OXO"," OXX  X O"," OXX  XO "," OXX  XOO"," OXX O   ",
" OXX O  X"," OXX O OX"," OXX O X "," OXX O XO"," OXX OO X"," OXX OOX "," OXX OOXX"," OXX OX  ",
" OXX OX O"," OXX OXO "," OXX OXOX"," OXX OXXO"," OXX X  O"," OXX X O "," OXX X OO"," OXX XO  ",
" OXX XO O"," OXX XOO "," OXX XOOX"," OXX XOXO"," OXX XXOO"," OXXO    "," OXXO   X"," OXXO  OX",
" OXXO  X "," OXXO  XO"," OXXO O X"," OXXO OX "," OXXO OXX"," OXXO X  "," OXXO X O"," OXXO XO ",
" OXXO XXO"," OXXOO  X"," OXXOO X "," OXXOO XX"," OXXOOOXX"," OXXOOX  "," OXXOOX X"," OXXOOXOX",
" OXXOOXX "," OXXOOXXO"," OXXOX   "," OXXOX  O"," OXXOX O "," OXXOX XO"," OXXOXO  "," OXXOXO X",
" OXXOXOX "," OXXOXOXO"," OXXOXX O"," OXXOXXOO"," OXXX   O"," OXXX  O "," OXXX  OO"," OXXX O  ",
" OXXX O O"," OXXX OO "," OXXX OOX"," OXXX OXO"," OXXX XOO"," OXXXO   "," OXXXO  O"," OXXXO O ",
" OXXXO OX"," OXXXO XO"," OXXXOO  "," OXXXOO X"," OXXXOOOX"," OXXXOOX "," OXXXOOXO"," OXXXOX O",
" OXXXOXO "," OXXXX OO"," OXXXXO O"," OXXXXOO "," X       "," X      O"," X     O "," X     OX",
" X     XO"," X    O  "," X    O X"," X    OOX"," X    OX "," X    OXO"," X    X O"," X    XO ",
" X    XOO"," X   O   "," X   O  X"," X   O OX"," X   O X "," X   O XO"," X   OO X"," X   OOX ",
" X   OOXX"," X   OX  "," X   OX O"," X   OXO "," X   OXOX"," X   OXXO"," X   X  O"," X   X O ",
" X   X OO"," X   XO  "," X   XO O"," X   XOO "," X   XOOX"," X   XOXO"," X   XXOO"," X  O    ",
" X  O   X"," X  O  OX"," X  O  X "," X  O  XO"," X  O O X"," X  O OX "," X  O OXX"," X  O X  ",
" X  O X O"," X  O XO "," X  O XOX"," X  O XXO"," X  OO  X"," X  OO X "," X  OO XX"," X  OOOXX",
" X  OOX  "," X  OOX X"," X  OOXOX"," X  OOXX "," X  OOXXO"," X  OX   "," X  OX  O"," X  OX O ",
" X  OX OX"," X  OX XO"," X  OXO  "," X  OXO X"," X  OXOOX"," X  OXOX "," X  OXOXO"," X  OXX O",
" X  OXXO "," X  OXXOO"," X  X   O"," X  X  O "," X  X  OO"," X  X O  "," X  X O O"," X  X OO ",
" X  X OOX"," X  X OXO"," X  X XOO"," X  XO   "," X  XO  O"," X  XO O "," X  XO OX"," X  XO XO",
" X  XOO  "," X  XOO X"," X  XOOOX"," X  XOOX "," X  XOX O"," X  XOXO "," X  XOXOO"," X  XX OO",
" X  XXO O"," X  XXOO "," X  XXOOO"," X O     "," X O    X"," X O   OX"," X O   X "," X O   XO",
" X O  O X"," X O  OX "," X O  OXX"," X O  X  "," X O  X O"," X O  XO "," X O  XOX"," X O  XXO",
" X O O  X"," X O O X "," X O O XX"," X O OOXX"," X O OX  "," X O OX X"," X O OXOX"," X O OXX ",
" X O OXXO"," X O X   "," X O X  O"," X O X O "," X O X OX"," X O X XO"," X O XO  "," X O XO X",
" X O XOOX"," X O XOX "," X O XOXO"," X O XX O"," X O XXO "," X O XXOO"," X OO   X"," X OO  X ",
" X OO  XX"," X OO OXX"," X OO X  "," X OO X X"," X OO XOX"," X OO XX "," X OO XXO"," X OOO XX",
" X OOOX X"," X OOOXX "," X OOX   "," X OOX  X"," X OOX OX"," X OOX X "," X OOX XO"," X OOXO X",
" X OOXOX "," X OOXOXX"," X OOXX  "," X OOXX O"," X OOXXO "," X OOXXOX"," X OOXXXO"," X OX    ",
" X OX   O"," X OX  O "," X OX  OX"," X OX  XO"," X OX O  "," X OX O X"," X OX OOX"," X OX OX ",
" X OX X O"," X OX XO "," X OX XOO"," X OXO   "," X OXO  X"," X OXO OX"," X OXO X "," X OXOO X",
" X OXOOXX"," X OXOX  "," X OXOX O"," X OXOXO "," X OXOXOX"," X OXOXXO"," X OXX  O"," X OXX O ",
" X OXX OO"," X OXXO  "," X OXXO O"," X OXXOO "," X OXXOOX"," X OXXOXO"," X OXXXOO"," X X    O",
" X X   O "," X X   OO"," X X  O  "," X X  O O"," X X  OO "," X X  OOX"," X X  OXO"," X X  XOO",
" X X O   "," X X O  O"," X X O O "," X X O OX"," X X O XO"," X X OO  "," X X OO X"," X X OOOX",
" X X OOX "," X X OOXO"," X X OX O"," X X OXO "," X X OXOO"," X X X OO"," X X XO O"," X X XOO ",
" X X XOOO"," X XO    "," X XO   O"," X XO  O "," X XO  OX"," X XO  XO"," X XO O  "," X XO O X",
" X XO OOX"," X XO OX "," X XO OXO"," X XO X O"," X XO XO "," X XO XOO"," X XOO   "," X XOO  X",
" X XOO OX"," X XOO X "," X XOO XO"," X XOOO X"," X XOOOX "," X XOOOXX"," X XOOX  "," X XOOX O",
" X XOOXO "," X XOOXOX"," X XOOXXO"," X XOX  O"," X XOX O "," X XOX OO"," X XOXO  "," X XOXO O",
" X XOXOO "," X XOXOOX"," X XOXOXO"," X XOXXOO"," X XX  OO"," X XX O O"," X XX OO "," X XX OOO",
" X XXO  O"," X XXO O "," X XXO OO"," X XXOO  "," X XXOO O"," X XXOOO "," X XXOOOX"," X XXOOXO",
" X XXOXOO"," XO      "," XO     X"," XO    OX"," XO    X "," XO    XO"," XO   O X"," XO   OX ",
" XO   OXX"," XO   X  "," XO   X O"," XO   XO "," XO   XOX"," XO   XXO"," XO  O  X"," XO  O X ",
" XO  O XX"," XO  OOXX"," XO  OX  "," XO  OX X"," XO  OXOX"," XO  OXX "," XO  OXXO"," XO  X   ",
" XO  X  O"," XO  X O "," XO  X OX"," XO  X XO"," XO  XO  "," XO  XO X"," XO  XOOX"," XO  XOX ",
" XO  XOXO"," XO  XX O"," XO  XXO "," XO  XXOO"," XO O   X"," XO O  X "," XO O  XX"," XO O OXX",
" XO O X  "," XO O X X"," XO O XOX"," XO O XX "," XO O XXO"," XO OO XX"," XO OOX X"," XO OOXX ",
" XO OOXXX"," XO OX   "," XO OX  X"," XO OX OX"," XO OX X "," XO OX XO"," XO OXO X"," XO OXOX ",
" XO OXX  "," XO OXX O"," XO OXXO "," XO OXXOX"," XO OXXXO"," XO X    "," XO X   O"," XO X  O ",
" XO X  OX"," XO X  XO"," XO X O  "," XO X O X"," XO X OOX"," XO X OX "," XO X X O"," XO X XO ",
" XO X XOO"," XO XO   "," XO XO  X"," XO XO OX"," XO XO X "," XO XOO X"," XO XOOXX"," XO XOX  ",
" XO XOX O"," XO XOXO "," XO XOXOX"," XO XX  O"," XO XX O "," XO XX OO"," XO XXO  "," XO XXO O",
" XO XXOO "," XO XXOOX"," XO XXOXO"," XO XXXOO"," XOO    X"," XOO   X "," XOO   XX"," XOO  OXX",
" XOO  X  "," XOO  X X"," XOO  XOX"," XOO  XX "," XOO  XXO"," XOO O XX"," XOO OX X"," XOO OXX ",
" XOO OXXX"," XOO X   "," XOO X  X"," XOO X OX"," XOO X X "," XOO X XO"," XOO XO X"," XOO XOX ",
" XOO XOXX"," XOO XX  "," XOO XX O"," XOO XXO "," XOO XXOX"," XOO XXXO"," XOOO  XX"," XOOO X X",
" XOOO XX "," XOOO XXX"," XOOOX  X"," XOOOX X "," XOOOX XX"," XOOOXOXX"," XOOOXX  "," XOOOXX X",
" XOOOXXOX"," XOOOXXX "," XOOOXXXO"," XOOX    "," XOOX   X"," XOOX  OX"," XOOX  X "," XOOX O X",
" XOOX OXX"," XOOX X  "," XOOX X O"," XOOX XO "," XOOX XOX"," XOOX XXO"," XOOXO  X"," XOOXO XX",
" XOOXOX  "," XOOXOX X"," XOOXOXOX"," XOOXOXX "," XOOXX   "," XOOXX  O"," XOOXX O "," XOOXX OX",
" XOOXX XO"," XOOXXO  "," XOOXXO X"," XOOXXOOX"," XOOXXOX "," XOOXXX O"," XOOXXXO "," XOOXXXOO",
" XOX     "," XOX    O"," XOX   O "," XOX   OX"," XOX   XO"," XOX  O  "," XOX  O X"," XOX  OOX",
" XOX  OX "," XOX  OXO"," XOX  X O"," XOX  XO "," XOX  XOO"," XOX O   "," XOX O  X"," XOX O OX",
" XOX O X "," XOX O XO"," XOX OO X"," XOX OOX "," XOX OOXX"," XOX OX  "," XOX OX O"," XOX OXO ",
" XOX OXOX"," XOX X  O"," XOX X O "," XOX X OO"," XOX XO  "," XOX XO O"," XOX XOO "," XOX XOOX",
" XOX XOXO"," XOX XXOO"," XOXO    "," XOXO   X"," XOXO  OX"," XOXO  X "," XOXO  XO"," XOXO O X",
" XOXO OX "," XOXO X  "," XOXO X O"," XOXO XO "," XOXO XOX"," XOXO XXO"," XOXOO  X"," XOXOO X ",
" XOXOO XX"," XOXOOOXX"," XOXOOX  "," XOXOOX X"," XOXOOXOX"," XOXOOXX "," XOXOOXXO"," XOXOX   ",
" XOXOX  O"," XOXOX O "," XOXOX OX"," XOXOX XO"," XOXOXO  "," XOXOXOOX"," XOXOXOXO"," XOXOXX O",
" XOXOXXO "," XOXOXXOO"," XOXX   O"," XOXX  O "," XOXX  OO"," XOXX O  "," XOXX O O"," XOXX OO ",
" XOXX OOX"," XOXX OXO"," XOXX XOO"," XOXXO   "," XOXXO  O"," XOXXO O "," XOXXO OX"," XOXXOO  ",
" XOXXOO X"," XOXXOOOX"," XOXXOOX "," XOXXOXO "," XOXXOXOO"," XOXXX OO"," XOXXXO O"," XOXXXOO ",
" XX     O"," XX    O "," XX    OO"," XX   O  "," XX   O O"," XX   OO "," XX   OOX"," XX   OXO",
" XX   XOO"," XX  O   "," XX  O  O"," XX  O O "," XX  O OX"," XX  O XO"," XX  OO  "," XX  OO X",
" XX  OOOX"," XX  OOX "," XX  OOXO"," XX  OX O"," XX  OXO "," XX  OXOO"," XX  X OO"," XX  XO O",
" XX  XOO "," XX  XOOO"," XX O    "," XX O   O"," XX O  O "," XX O  OX"," XX O  XO"," XX O O  ",
" XX O O X"," XX O OOX"," XX O OX "," XX O OXO"," XX O X O"," XX O XO "," XX O XOO"," XX OO   ",
" XX OO  X"," XX OO OX"," XX OO X "," XX OO XO"," XX OOO X"," XX OOOX "," XX OOOXX"," XX OOX  ",
" XX OOX O"," XX OOXO "," XX OOXOX"," XX OOXXO"," XX OX  O"," XX OX O "," XX OX OO"," XX OXO  ",
" XX OXO O"," XX OXOO "," XX OXOOX"," XX OXOXO"," XX OXXOO"," XX X  OO"," XX X O O"," XX X OO ",
" XX X OOO"," XX XO  O"," XX XO O "," XX XO OO"," XX XOO  "," XX XOO O"," XX XOOO "," XX XOOOX",
" XX XOOXO"," XX XOXOO"," XXO     "," XXO    O"," XXO   O "," XXO   OX"," XXO   XO"," XXO  O  ",
" XXO  O X"," XXO  OOX"," XXO  OX "," XXO  OXO"," XXO  X O"," XXO  XO "," XXO  XOO"," XXO O   ",
" XXO O  X"," XXO O OX"," XXO O X "," XXO O XO"," XXO OO X"," XXO OOX "," XXO OOXX"," XXO OX  ",
" XXO OX O"," XXO OXO "," XXO OXOX"," XXO OXXO"," XXO X  O"," XXO X O "," XXO X OO"," XXO XO  ",
" XXO XO O"," XXO XOO "," XXO XOOX"," XXO XOXO"," XXO XXOO"," XXOO    "," XXOO   X"," XXOO  OX",
" XXOO  X "," XXOO  XO"," XXOO O X"," XXOO OX "," XXOO OXX"," XXOO X  "," XXOO X O"," XXOO XO ",
" XXOO XOX"," XXOO XXO"," XXOOO  X"," XXOOO X "," XXOOOOXX"," XXOOOX  "," XXOOOXOX"," XXOOOXXO",
" XXOOX   "," XXOOX  O"," XXOOX O "," XXOOX OX"," XXOOX XO"," XXOOXO  "," XXOOXO X"," XXOOXOX ",
" XXOOXOXO"," XXOOXX O"," XXOOXXO "," XXOOXXOO"," XXOX   O"," XXOX  O "," XXOX  OO"," XXOX O  ",
" XXOX O O"," XXOX OO "," XXOX OOX"," XXOX OXO"," XXOX XOO"," XXOXO   "," XXOXO  O"," XXOXO O ",
" XXOXO OX"," XXOXO XO"," XXOXOO  "," XXOXOO X"," XXOXOOOX"," XXOXOOX "," XXOXOX O"," XXOXOXO ",
" XXOXX OO"," XXOXXO O"," XXOXXOO "," XXOXXOOO"," XXX   OO"," XXX  O O"," XXX  OO "," XXX  OOO",
" XXX O  O"," XXX O O "," XXX O OO"," XXX OO  "," XXX OO O"," XXX OOO "," XXX OOOX"," XXX OOXO",
" XXX OXOO"," XXXO   O"," XXXO  O "," XXXO  OO"," XXXO O  "," XXXO O O"," XXXO OO "," XXXO OOX",
" XXXO OXO"," XXXO XOO"," XXXOO   "," XXXOO  O"," XXXOO O "," XXXOO OX"," XXXOO XO"," XXXOOO  ",
" XXXOOO X"," XXXOOOOX"," XXXOOOX "," XXXOOOXO"," XXXOOX O"," XXXOOXO "," XXXOOXOO"," XXXOX OO",
" XXXOXO O"," XXXOXOO "," XXXOXOOO"," XXXXO OO"," XXXXOO O"," XXXXOOO "," XXXXOOOO","O       X",
"O      X ","O      XX","O     OXX","O     X  ","O     X X","O     XOX","O     XX ","O     XXO",
"O    O XX","O    OX X","O    OXX ","O    OXXX","O    X   ","O    X  X","O    X OX","O    X X ",
"O    X XO","O    XO X","O    XOX ","O    XOXX","O    XX  ","O    XX O","O    XXO ","O    XXOX",
"O    XXXO","O   O  XX","O   O X X","O   O XX ","O   O XXX","O   OX  X","O   OX X ","O   OX XX",
"O   OXOXX","O   OXX  ","O   OXX X","O   OXXOX","O   OXXX ","O   OXXXO","O   X    ","O   X   X",
"O   X  OX","O   X  X ","O   X  XO","O   X O X","O   X OX ","O   X OXX","O   X X  ","O   X X O",
"O   X XO ","O   X XOX","O   X XXO","O   XO  X","O   XO X ","O   XO XX","O   XOOXX","O   XOX  ",
"O   XOX X","O   XOXOX","O   XOXX ","O   XOXXO","O   XX   ","O   XX  O","O   XX O ","O   XX OX",
"O   XX XO","O   XXO  ","O   XXO X","O   XXOOX","O   XXOX ","O   XXOXO","O   XXX O","O   XXXO ",
"O   XXXOO","O  O   XX","O  O  X X","O  O  XX ","O  O  XXX","O  O X  X","O  O X X ","O  O X XX",
"O  O XOXX","O  O XX  ","O  O XX X","O  O XXOX","O  O XXX ","O  O XXXO","O  OOX XX","O  OOXX X",
"O  OOXXX ","O  OOXXXX","O  OX   X","O  OX  X ","O  OX  XX","O  OX OXX","O  OX X  ","O  OX X X",
"O  OX XOX","O  OX XX ","O  OX XXO","O  OXO XX","O  OXOX X","O  OXOXX ","O  OXOXXX","O  OXX   ",
"O  OXX  X","O  OXX OX","O  OXX X ","O  OXX XO","O  OXXO X","O  OXXOX ","O  OXXX  ","O  OXXX O",
"O  OXXXO ","O  OXXXOX","O  OXXXXO","O  X     ","O  X    X","O  X   OX","O  X   X ","O  X   XO",
"O  X  O X","O  X  OX ","O  X  OXX","O  X  X  ","O  X  X O","O  X  XO ","O  X  XOX","O  X  XXO",
"O  X O  X","O  X O X ","O  X O XX","O  X OOXX","O  X OX  ","O  X OX X","O  X OXOX","O  X OXX ",
"O  X OXXO","O  X X   ","O  X X  O","O  X X O ","O  X X OX","O  X X XO","O  X XO  ","O  X XO X",
"O  X XOOX","O  X XOX ","O  X XOXO","O  X XX O","O  X XXO ","O  X XXOO","O  XO   X","O  XO  X ",
"O  XO  XX","O  XO OXX","O  XO X  ","O  XO X X","O  XO XOX","O  XO XX ","O  XO XXO","O  XOO XX",
"O  XOOX X","O  XOOXX ","O  XOOXXX","O  XOX   ","O  XOX  X","O  XOX OX","O  XOX X ","O  XOX XO",
"O  XOXO X","O  XOXOX ","O  XOXOXX","O  XOXX  ","O  XOXX O","O  XOXXO ","O  XOXXOX","O  XX    ",
"O  XX   O","O  XX  O ","O  XX  OX","O  XX  XO","O  XX O  ","O  XX O X","O  XX OOX","O  XX OX ",
"O  XX OXO","O  XX X O","O  XX XO ","O  XX XOO","O  XXO   ","O  XXO  X","O  XXO OX","O  XXO X ",
"O  XXO XO","O  XXOO X","O  XXOOX ","O  XXOOXX","O  XXOX  ","O  XXOX O","O  XXOXO ","O  XXOXOX",
"O  XXOXXO","O  XXX  O","O  XXX O ","O  XXXO  ","O  XXXOOX","O  XXXOXO","O  XXXXOO","O O    XX",
"O O   X X","O O   XX ","O O   XXX","O O  X  X","O O  X X ","O O  X XX","O O  XOXX","O O  XX  ",
"O O  XX X","O O  XXOX","O O  XXX ","O O  XXXO","O O OX XX","O O OXX X","O O OXXX ","O O OXXXX",
"O O X   X","O O X  X ","O O X  XX","O O X OXX","O O X X  ","O O X X X","O O X XOX","O O X XX ",
"O O X XXO","O O XO XX","O O XOX X","O O XOXX ","O O XOXXX","O O XX   ","O O XX  X","O O XX OX",
"O O XX X ","O O XX XO","O O XXO X","O O XXOX ","O O XXOXX","O O XXX  ","O O XXX O","O O XXXO ",
"O O XXXOX","O O XXXXO","O OO X XX","O OO XX X","O OO XXX ","O OO XXXX","O OOX  XX","O OOX X X",
"O OOX XX ","O OOX XXX","O OOXX  X","O OOXX X ","O OOXX XX","O OOXXOXX","O OOXXX  ","O OOXXX X",
"O OOXXXOX","O OOXXXX ","O OOXXXXO","O OX    X","O OX   X ","O OX   XX","O OX  OXX","O OX  X  ",
"O OX  X X","O OX  XOX","O OX  XX ","O OX  XXO","O OX O XX","O OX OX X","O OX OXX ","O OX OXXX",
"O OX X   ","O OX X  X","O OX X OX","O OX X X ","O OX X XO","O OX XO X","O OX XOX ","O OX XOXX",
"O OX XX  ","O OX XX O","O OX XXO ","O OX XXOX","O OX XXXO","O OXO  XX","O OXO X X","O OXO XX ",
"O OXO XXX","O OXOX  X","O OXOX X ","O OXOX XX","O OXOXOXX","O OXOXX  ","O OXOXX X","O OXOXXOX",
"O OXOXXX ","O OXOXXXO","O OXX    ","O OXX   X","O OXX  OX","O OXX  X ","O OXX  XO","O OXX O X",
"O OXX OX ","O OXX OXX","O OXX X  ","O OXX X O","O OXX XO ","O OXX XOX","O OXX XXO","O OXXO  X",
"O OXXO X ","O OXXO XX","O OXXOOXX","O OXXOX  ","O OXXOX X","O OXXOXOX","O OXXOXX ","O OXXOXXO",
"O OXXX   ","O OXXX OX","O OXXX XO","O OXXXO X","O OXXXOX ","O OXXXX O","O OXXXXO ","O X      ",
"O X     X","O X    OX","O X    X ","O X    XO","O X   O X","O X   OX ","O X   OXX","O X   X  ",
"O X   X O","O X   XO ","O X   XOX","O X   XXO","O X  O  X","O X  O X ","O X  O XX","O X  OOXX",
"O X  OX  ","O X  OX X","O X  OXOX","O X  OXX ","O X  OXXO","O X  X   ","O X  X  O","O X  X O ",
"O X  X OX","O X  X XO","O X  XO  ","O X  XO X","O X  XOX ","O X  XOXO","O X  XX O","O X  XXO ",
"O X  XXOO","O X O   X","O X O  X ","O X O  XX","O X O OXX","O X O X  ","O X O X X","O X O XOX",
"O X O XX ","O X O XXO","O X OO XX","O X OOX X","O X OOXX ","O X OOXXX","O X OX   ","O X OX  X",
"O X OX X ","O X OX XO","O X OXOX ","O X OXOXX","O X OXX  ","O X OXX O","O X OXXO ","O X OXXOX",
"O X X    ","O X X   O","O X X  O ","O X X  OX","O X X  XO","O X X O  ","O X X O X","O X X OOX",
"O X X OX ","O X X OXO","O X X X O","O X X XO ","O X XO   ","O X XO  X","O X XO OX","O X XO X ",
"O X XO XO","O X XOO X","O X XOOX ","O X XOOXX","O X XOX  ","O X XOXOX","O X XOXXO","O X XX  O",
"O X XX O ","O X XX OO","O X XXO  ","O X XXO O","O X XXOO ","O X XXOOX","O X XXOXO","O X XXXOO",
"O XO    X","O XO   X ","O XO   XX","O XO  OXX","O XO  X  ","O XO  X X","O XO  XOX","O XO  XX ",
"O XO  XXO","O XO O XX","O XO OX X","O XO OXX ","O XO OXXX","O XO X   ","O XO X  X","O XO X X ",
"O XO X XO","O XO XOX ","O XO XX  ","O XO XX O","O XO XXO ","O XO XXOX","O XO XXXO","O XOO  XX",
"O XOO X X","O XOO XX ","O XOO XXX","O XOOX X ","O XOOX XX","O XOOXX  ","O XOOXX X","O XOOXXX ",
"O XOOXXXO","O XOX    ","O XOX   X","O XOX  OX","O XOX  X ","O XOX  XO","O XOX O X","O XOX OX ",
"O XOX X  ","O XOX XOX","O XOX XXO","O XOXO  X","O XOXO X ","O XOXO XX","O XOXOOXX","O XOXOX X",
"O XOXOXX ","O XOXX   ","O XOXX  O","O XOXX O ","O XOXX OX","O XOXX XO","O XOXXO  ","O XOXXOXO",
"O XOXXX O","O XOXXXO ","O XX     ","O XX    O","O XX   O ","O XX   OX","O XX   XO","O XX  O  ",
"O XX  O X","O XX  OOX","O XX  OX ","O XX  OXO","O XX  X O","O XX  XO ","O XX  XOO","O XX O   ",
"O XX O  X","O XX O OX","O XX O X ","O XX O XO","O XX OO X","O XX OOX ","O XX OOXX","O XX OX  ",
"O XX OX O","O XX OXO ","O XX OXOX","O XX OXXO","O XX X  O","O XX X O ","O XX X OO","O XX XO  ",
"O XX XO O","O XX XOO ","O XX XOOX","O XX XOXO","O XX XXOO","O XXO    ","O XXO   X","O XXO  OX",
"O XXO  X ","O XXO  XO","O XXO O X","O XXO OX ","O XXO OXX","O XXO X  ","O XXO X O","O XXO XO ",
"O XXO XOX","O XXOO  X","O XXOO X ","O XXOO XX","O XXOOOXX","O XXOOX  ","O XXOOX X","O XXOOXOX",
"O XXOOXX ","O XXOOXXO","O XXOX   ","O XXOX  O","O XXOX O ","O XXOX OX","O XXOXO  ","O XXOXO X",
"O XXOXOX ","O XXOXOXO","O XXOXXO ","O XXOXXOO","O XXX   O","O XXX  O ","O XXX  OO","O XXX O  ",
"O XXX O O","O XXX OO ","O XXX OOX","O XXX OXO","O XXX XOO","O XXXO   ","O XXXO  O","O XXXO O ",
"O XXXO OX","O XXXO XO","O XXXOO  ","O XXXOO X","O XXXOOOX","O XXXOOX ","O XXXOOXO","O XXXOX O",
"O XXXOXO ","O XXXX OO","O XXXXO O","O XXXXOO ","OO     XX","OO    X X","OO    XX ","OO    XXX",
"OO   X  X","OO   X X ","OO   X XX","OO   XOXX","OO   XX  ","OO   XX X","OO   XXOX","OO   XXX ",
"OO   XXXO","OO  OX XX","OO  OXX X","OO  OXXX ","OO  OXXXX","OO  X   X","OO  X  X ","OO  X  XX",
"OO  X OXX","OO  X X  ","OO  X X X","OO  X XOX","OO  X XX ","OO  X XXO","OO  XO XX","OO  XOX X",
"OO  XOXX ","OO  XOXXX","OO  XX   ","OO  XX  X","OO  XX OX","OO  XX X ","OO  XX XO","OO  XXO X",
"OO  XXOX ","OO  XXOXX","OO  XXX  ","OO  XXX O","OO  XXXO ","OO  XXXOX","OO  XXXXO","OO O X XX",
"OO O XX X","OO O XXX ","OO O XXXX","OO OX  XX","OO OX X X","OO OX XX ","OO OX XXX","OO OXX  X",
"OO OXX X ","OO OXX XX","OO OXXOXX","OO OXXX  ","OO OXXX X","OO OXXXOX","OO OXXXX ","OO OXXXXO",
"OO X    X","OO X   X ","OO X   XX","OO X  OXX","OO X  X  ","OO X  X X","OO X  XOX","OO X  XX ",
"OO X  XXO","OO X O XX","OO X OX X","OO X OXX ","OO X OXXX","OO X X   ","OO X X  X","OO X X OX",
"OO X X X ","OO X X XO","OO X XO X","OO X XOX ","OO X XOXX","OO X XX  ","OO X XX O","OO X XXO ",
"OO X XXOX","OO X XXXO","OO XO  XX","OO XO X X","OO XO XX ","OO XO XXX","OO XOX  X","OO XOX X ",
"OO XOX XX","OO XOXOXX","OO XOXX  ","OO XOXX X","OO XOXXOX","OO XOXXX ","OO XOXXXO","OO XX    ",
"OO XX   X","OO XX  OX","OO XX  X ","OO XX  XO","OO XX O X","OO XX OX ","OO XX OXX","OO XX X  ",
"OO XX X O","OO XX XO ","OO XX XOX","OO XX XXO","OO XXO  X","OO XXO X ","OO XXO XX","OO XXOOXX",
"OO XXOX  ","OO XXOX X","OO XXOXOX","OO XXOXX ","OO XXOXXO","OO XXX   ","OO XXX OX","OO XXX XO",
"OO XXXO X","OO XXXOX ","OO XXXX O","OO XXXXO ","OOO  X XX","OOO  XX X","OOO  XXX ","OOO X  XX",
"OOO X X X","OOO X XX ","OOO XX  X","OOO XX X ","OOO XXOXX","OOO XXX  ","OOO XXXOX","OOO XXXXO",
"OOOOXX XX","OOOOXXX X","OOOOXXXX ","OOOX   XX","OOOX  X X","OOOX  XX ","OOOX X  X","OOOX X X ",
"OOOX XOXX","OOOX XX  ","OOOX XXOX","OOOX XXXO","OOOXOX XX","OOOXOXX X","OOOXOXXX ","OOOXX   X",
"OOOXX  X ","OOOXX OXX","OOOXX X  ","OOOXX XOX","OOOXX XXO","OOOXXO XX","OOOXXOX X","OOOXXOXX ",
"OOX     X","OOX    X ","OOX    XX","OOX   OXX","OOX   X  ","OOX   X X","OOX   XOX","OOX   XX ",
"OOX   XXO","OOX  O XX","OOX  OX X","OOX  OXX ","OOX  OXXX","OOX  X   ","OOX  X  X","OOX  X X ",
"OOX  X XO","OOX  XOX ","OOX  XOXX","OOX  XX  ","OOX  XX O","OOX  XXO ","OOX  XXOX","OOX  XXXO",
"OOX O  XX","OOX O X X","OOX O XX ","OOX O XXX","OOX OX X ","OOX OX XX","OOX OXX  ","OOX OXX X",
"OOX OXXX ","OOX OXXXO","OOX X    ","OOX X   X","OOX X  OX","OOX X  X ","OOX X  XO","OOX X O X",
"OOX X OX ","OOX X OXX","OOX X X  ","OOX X XOX","OOX X XXO","OOX XO  X","OOX XO X ","OOX XO XX",
"OOX XOOXX","OOX XOX X","OOX XOXX ","OOX XX   ","OOX XX  O","OOX XX O ","OOX XX OX","OOX XX XO",
"OOX XXO  ","OOX XXO X","OOX XXOX ","OOX XXOXO","OOX XXX O","OOX XXXO ","OOXO   XX","OOXO  X X",
"OOXO  XX ","OOXO  XXX","OOXO X X ","OOXO X XX","OOXO XX  ","OOXO XX X","OOXO XXX ","OOXO XXXO",
"OOXOOXXX ","OOXOOXXXX","OOXOX   X","OOXOX  X ","OOXOX  XX","OOXOX OXX","OOXOX X X","OOXOX XX ",
"OOXOXO XX","OOXOXOXXX","OOXOXX   ","OOXOXX  X","OOXOXX X ","OOXOXX XO","OOXOXXOX ","OOXOXXX  ",
"OOXOXXXOX","OOXOXXXXO","OOXX     ","OOXX    X","OOXX   OX","OOXX   X ","OOXX   XO","OOXX  O X",
"OOXX  OX ","OOXX  OXX","OOXX  X  ","OOXX  X O","OOXX  XO ","OOXX  XOX","OOXX  XXO","OOXX O  X",
"OOXX O X ","OOXX O XX","OOXX OOXX","OOXX OX  ","OOXX OX X","OOXX OXOX","OOXX OXX ","OOXX OXXO",
"OOXX X   ","OOXX X  O","OOXX X O ","OOXX X OX","OOXX X XO","OOXX XO  ","OOXX XO X","OOXX XOX ",
"OOXX XOXO","OOXX XX O","OOXX XXO ","OOXX XXOO","OOXXO   X","OOXXO  X ","OOXXO  XX","OOXXO OXX",
"OOXXO X  ","OOXXO X X","OOXXO XOX","OOXXO XX ","OOXXO XXO","OOXXOO XX","OOXXOOX X","OOXXOOXX ",
"OOXXOOXXX","OOXXOX   ","OOXXOX  X","OOXXOX X ","OOXXOX XO","OOXXOXOX ","OOXXOXOXX","OOXXOXX  ",
"OOXXOXX O","OOXXOXXO ","OOXXX    ","OOXXX   O","OOXXX  O ","OOXXX  OX","OOXXX  XO","OOXXX O  ",
"OOXXX O X","OOXXX OOX","OOXXX OX ","OOXXX OXO","OOXXX X O","OOXXX XO ","OOXXXO   ","OOXXXO  X",
"OOXXXO OX","OOXXXO X ","OOXXXO XO","OOXXXOO X","OOXXXOOX ","OOXXXOOXX","OOXXXOX  ","OOXXXOXOX",
"OOXXXOXXO","OOXXXX  O","OOXXXX O ","OOXXXXO  ","OOXXXXOOX","OOXXXXOXO","OOXXXXXOO","OX       ",
"OX      X","OX     OX","OX     X ","OX     XO","OX    O X","OX    OX ","OX    OXX","OX    X  ",
"OX    X O","OX    XO ","OX    XOX","OX    XXO","OX   O  X","OX   O X ","OX   O XX","OX   OOXX",
"OX   OX  ","OX   OX X","OX   OXOX","OX   OXX ","OX   OXXO","OX   X   ","OX   X  O","OX   X O ",
"OX   X OX","OX   X XO","OX   XO  ","OX   XO X","OX   XOOX","OX   XOX ","OX   XOXO","OX   XX O",
"OX   XXO ","OX   XXOO","OX  O   X","OX  O  X ","OX  O  XX","OX  O OXX","OX  O X  ","OX  O X X",
"OX  O XOX","OX  O XX ","OX  O XXO","OX  OO XX","OX  OOX X","OX  OOXX ","OX  OOXXX","OX  OX   ",
"OX  OX  X","OX  OX OX","OX  OX X ","OX  OX XO","OX  OXO X","OX  OXOX ","OX  OXOXX","OX  OXX  ",
"OX  OXX O","OX  OXXO ","OX  OXXOX","OX  X    ","OX  X   O","OX  X  O ","OX  X  OX","OX  X  XO",
"OX  X O  ","OX  X O X","OX  X OOX","OX  X OX ","OX  X X O","OX  X XO ","OX  X XOO","OX  XO   ",
"OX  XO  X","OX  XO OX","OX  XO X ","OX  XOO X","OX  XOOXX","OX  XOX  ","OX  XOX O","OX  XOXO ",
"OX  XOXOX","OX  XOXXO","OX  XX  O","OX  XX O ","OX  XX OO","OX  XXO  ","OX  XXO O","OX  XXOO ",
"OX  XXOOX","OX  XXOXO","OX  XXXOO","OX O    X","OX O   X ","OX O   XX","OX O  OXX","OX O  X  ",
"OX O  X X","OX O  XOX","OX O  XX ","OX O  XXO","OX O O XX","OX O OX X","OX O OXX ","OX O OXXX",
"OX O X   ","OX O X  X","OX O X OX","OX O X X ","OX O X XO","OX O XO X","OX O XOX ","OX O XX  ",
"OX O XX O","OX O XXO ","OX O XXOX","OX O XXXO","OX OO  XX","OX OO X X","OX OO XX ","OX OO XXX",
"OX OOX  X","OX OOX X ","OX OOX XX","OX OOXOXX","OX OOXX  ","OX OOXX X","OX OOXXOX","OX OOXXX ",
"OX OOXXXO","OX OX    ","OX OX   X","OX OX  OX","OX OX  X ","OX OX O X","OX OX X  ","OX OX X O",
"OX OX XO ","OX OX XOX","OX OX XXO","OX OXO  X","OX OXO XX","OX OXOX  ","OX OXOX X","OX OXOXOX",
"OX OXOXX ","OX OXX   ","OX OXX  O","OX OXX O ","OX OXX OX","OX OXX XO","OX OXXO  ","OX OXXOOX",
"OX OXXX O","OX OXXXO ","OX OXXXOO","OX X     ","OX X    O","OX X   O ","OX X   OX","OX X   XO",
"OX X  O  ","OX X  O X","OX X  OOX","OX X  OX ","OX X  OXO","OX X  X O","OX X  XO ","OX X  XOO",
"OX X O   ","OX X O  X","OX X O OX","OX X O X ","OX X O XO","OX X OO X","OX X OOX ","OX X OOXX",
"OX X OX  ","OX X OX O","OX X OXO ","OX X OXOX","OX X OXXO","OX X X  O","OX X X O ","OX X X OO",
"OX X XO  ","OX X XO O","OX X XOO ","OX X XOOX","OX X XOXO","OX X XXOO","OX XO    ","OX XO   X",
"OX XO  OX","OX XO  X ","OX XO  XO","OX XO O X","OX XO OX ","OX XO OXX","OX XO X  ","OX XO X O",
"OX XO XO ","OX XO XOX","OX XOO  X","OX XOO X ","OX XOO XX","OX XOOOXX","OX XOOX  ","OX XOOX X",
"OX XOOXOX","OX XOOXX ","OX XOOXXO","OX XOX   ","OX XOX  O","OX XOX O ","OX XOX OX","OX XOXO  ",
"OX XOXO X","OX XOXOOX","OX XOXOX ","OX XOXOXO","OX XOXXO ","OX XOXXOO","OX XX   O","OX XX  O ",
"OX XX  OO","OX XX O  ","OX XX O O","OX XX OO ","OX XX OOX","OX XX OXO","OX XX XOO","OX XXO   ",
"OX XXO  O","OX XXO O ","OX XXO OX","OX XXO XO","OX XXOO  ","OX XXOO X","OX XXOOOX","OX XXOOX ",
"OX XXOX O","OX XXOXO ","OX XXOXOO","OX XXX OO","OX XXXO O","OX XXXOO ","OXO     X","OXO    X ",
"OXO    XX","OXO   OXX","OXO   X  ","OXO   X X","OXO   XOX","OXO   XX ","OXO   XXO","OXO  O XX",
"OXO  OX X","OXO  OXX ","OXO  OXXX","OXO  X   ","OXO  X  X","OXO  X OX","OXO  X X ","OXO  X XO",
"OXO  XO X","OXO  XOX ","OXO  XOXX","OXO  XX  ","OXO  XX O","OXO  XXO ","OXO  XXOX","OXO  XXXO",
"OXO O  XX","OXO O X X","OXO O XX ","OXO O XXX","OXO OX  X","OXO OX X ","OXO OX XX","OXO OXOXX",
"OXO OXX  ","OXO OXX X","OXO OXXOX","OXO OXXX ","OXO OXXXO","OXO X    ","OXO X   X","OXO X  OX",
"OXO X  X ","OXO X O X","OXO X OXX","OXO X X  ","OXO X X O","OXO X XO ","OXO X XOX","OXO X XXO",
"OXO XO  X","OXO XO XX","OXO XOX  ","OXO XOX X","OXO XOXOX","OXO XOXX ","OXO XX   ","OXO XX  O",
"OXO XX O ","OXO XX OX","OXO XX XO","OXO XXO  ","OXO XXO X","OXO XXOOX","OXO XXOX ","OXO XXX O",
"OXO XXXO ","OXO XXXOO","OXOO   XX","OXOO  X X","OXOO  XX ","OXOO  XXX","OXOO X  X","OXOO X X ",
"OXOO X XX","OXOO XOXX","OXOO XX  ","OXOO XX X","OXOO XXOX","OXOO XXX ","OXOO XXXO","OXOOOX XX",
"OXOOOXX X","OXOOOXXX ","OXOOOXXXX","OXOOX   X","OXOOX  XX","OXOOX X  ","OXOOX X X","OXOOX XOX",
"OXOOX XX ","OXOOXOX X","OXOOXOXXX","OXOOXX   ","OXOOXX  X","OXOOXX OX","OXOOXX X ","OXOOXXO X",
"OXOOXXX  ","OXOOXXX O","OXOOXXXO ","OXOOXXXOX","OXOOXXXXO","OXOX     ","OXOX    X","OXOX   OX",
"OXOX   X ","OXOX   XO","OXOX  O X","OXOX  OX ","OXOX  OXX","OXOX  X  ","OXOX  X O","OXOX  XO ",
"OXOX  XOX","OXOX  XXO","OXOX O  X","OXOX O X ","OXOX O XX","OXOX OOXX","OXOX OX  ","OXOX OX X",
"OXOX OXOX","OXOX OXX ","OXOX OXXO","OXOX X   ","OXOX X  O","OXOX X O ","OXOX X OX","OXOX X XO",
"OXOX XO  ","OXOX XO X","OXOX XOOX","OXOX XOX ","OXOX XOXO","OXOX XX O","OXOX XXO ","OXOX XXOO",
"OXOXO   X","OXOXO  X ","OXOXO  XX","OXOXO OXX","OXOXO X  ","OXOXO X X","OXOXO XOX","OXOXO XX ",
"OXOXO XXO","OXOXOO XX","OXOXOOX X","OXOXOOXX ","OXOXOOXXX","OXOXOX   ","OXOXOX  X","OXOXOX OX",
"OXOXOX X ","OXOXOX XO","OXOXOXO X","OXOXOXOX ","OXOXOXX  ","OXOXOXX O","OXOXOXXO ","OXOXOXXOX",
"OXOXX    ","OXOXX   O","OXOXX  O ","OXOXX  OX","OXOXX  XO","OXOXX O  ","OXOXX O X","OXOXX OOX",
"OXOXX OX ","OXOXX X O","OXOXX XO ","OXOXX XOO","OXOXXO   ","OXOXXO  X","OXOXXO OX","OXOXXO X ",
"OXOXXOO X","OXOXXOOXX","OXOXXOX  ","OXOXXOX O","OXOXXOXO ","OXOXXOXOX","OXOXXX  O","OXOXXX O ",
"OXOXXXO  ","OXOXXXOOX","OXOXXXOXO","OXOXXXXOO","OXX      ","OXX     O","OXX    O ","OXX    OX",
"OXX    XO","OXX   O  ","OXX   O X","OXX   OOX","OXX   OX ","OXX   OXO","OXX   X O","OXX   XO ",
"OXX   XOO","OXX  O   ","OXX  O  X","OXX  O OX","OXX  O X ","OXX  O XO","OXX  OO X","OXX  OOX ",
"OXX  OOXX","OXX  OX  ","OXX  OX O","OXX  OXO ","OXX  OXOX","OXX  OXXO","OXX  X  O","OXX  X O ",
"OXX  X OO","OXX  XO  ","OXX  XO O","OXX  XOO ","OXX  XOOX","OXX  XOXO","OXX  XXOO","OXX O    ",
"OXX O   X","OXX O  OX","OXX O  X ","OXX O  XO","OXX O O X","OXX O OX ","OXX O OXX","OXX O X  ",
"OXX O X O","OXX O XO ","OXX O XOX","OXX OO  X","OXX OO X ","OXX OO XX","OXX OOOXX","OXX OOX  ",
"OXX OOX X","OXX OOXOX","OXX OOXX ","OXX OOXXO","OXX OX   ","OXX OX  O","OXX OX O ","OXX OX OX",
"OXX OXO  ","OXX OXO X","OXX OXOX ","OXX OXOXO","OXX OXXO ","OXX OXXOO","OXX X   O","OXX X  O ",
"OXX X  OO","OXX X O  ","OXX X O O","OXX X OO ","OXX X OOX","OXX X OXO","OXX X XOO","OXX XO   ",
"OXX XO  O","OXX XO O ","OXX XO OX","OXX XO XO","OXX XOO  ","OXX XOO X","OXX XOOOX","OXX XOOX ",
"OXX XOX O","OXX XOXO ","OXX XX OO","OXX XXO O","OXX XXOO ","OXX XXOOO","OXXO     ","OXXO    X",
"OXXO   OX","OXXO   X ","OXXO   XO","OXXO  O X","OXXO  OX ","OXXO  X  ","OXXO  X O","OXXO  XO ",
"OXXO  XOX","OXXO  XXO","OXXO O  X","OXXO O X ","OXXO O XX","OXXO OOXX","OXXO OX  ","OXXO OX X",
"OXXO OXOX","OXXO OXX ","OXXO OXXO","OXXO X   ","OXXO X  O","OXXO X O ","OXXO X OX","OXXO X XO",
"OXXO XO  ","OXXO XOXO","OXXO XX O","OXXO XXO ","OXXO XXOO","OXXOO   X","OXXOO  X ","OXXOO  XX",
"OXXOO OXX","OXXOO X  ","OXXOO X X","OXXOO XOX","OXXOO XX ","OXXOO XXO","OXXOOO XX","OXXOOOX X",
"OXXOOOXX ","OXXOOX   ","OXXOOX  X","OXXOOX X ","OXXOOX XO","OXXOOXOX ","OXXOOXX  ","OXXOOXX O",
"OXXOOXXO ","OXXOOXXOX","OXXOX    ","OXXOX   O","OXXOX  O ","OXXOX  OX","OXXOX  XO","OXXOX O  ",
"OXXOX OOX","OXXOX X O","OXXOX XO ","OXXOXO   ","OXXOXO  X","OXXOXO OX","OXXOXO X ","OXXOXOO X",
"OXXOXOX  ","OXXOXOXOX","OXXOXOXXO","OXXOXX  O","OXXOXX O ","OXXOXX OO","OXXOXXO O","OXXOXXOO ",
"OXXOXXXOO","OXXX    O","OXXX   O ","OXXX   OO","OXXX  O  ","OXXX  O O","OXXX  OO ","OXXX  OOX",
"OXXX  OXO","OXXX  XOO","OXXX O   ","OXXX O  O","OXXX O O ","OXXX O OX","OXXX O XO","OXXX OO  ",
"OXXX OO X","OXXX OOOX","OXXX OOX ","OXXX OOXO","OXXX OX O","OXXX OXO ","OXXX OXOO","OXXX X OO",
"OXXX XO O","OXXX XOO ","OXXX XOOO","OXXXO    ","OXXXO   O","OXXXO  O ","OXXXO  OX","OXXXO O  ",
"OXXXO O X","OXXXO OOX","OXXXO OX ","OXXXO OXO","OXXXO XO ","OXXXO XOO","OXXXOO   ","OXXXOO  X",
"OXXXOO OX","OXXXOO X ","OXXXOO XO","OXXXOOO X","OXXXOOOX ","OXXXOOOXX","OXXXOOX  ","OXXXOOX O",
"OXXXOOXO ","OXXXOOXOX","OXXXOX O ","OXXXOX OO","OXXXOXO  ","OXXXOXO O","OXXXOXOO ","OXXXOXOOX",
"OXXXX  OO","OXXXX O O","OXXXX OO ","OXXXX OOO","OXXXXO  O","OXXXXO O ","OXXXXO OO","OXXXXOO  ",
"OXXXXOO O","OXXXXOOO ","OXXXXOOOX","OXXXXOOXO","OXXXXOXOO","X        ","X       O","X      O ",
"X      OX","X      XO","X     O  ","X     O X","X     OOX","X     OX ","X     OXO","X     X O",
"X     XO ","X     XOO","X    O   ","X    O  X","X    O OX","X    O X ","X    O XO","X    OO X",
"X    OOX ","X    OOXX","X    OX  ","X    OX O","X    OXO ","X    OXOX","X    OXXO","X    X  O",
"X    X O ","X    X OO","X    XO  ","X    XO O","X    XOO ","X    XOOX","X    XOXO","X    XXOO",
"X   O    ","X   O   X","X   O  OX","X   O  X ","X   O  XO","X   O O X","X   O OX ","X   O OXX",
"X   O X  ","X   O X O","X   O XO ","X   O XOX","X   O XXO","X   OO  X","X   OO X ","X   OO XX",
"X   OOOXX","X   OOX  ","X   OOX X","X   OOXOX","X   OOXX ","X   OOXXO","X   OX   ","X   OX  O",
"X   OX O ","X   OX OX","X   OX XO","X   OXO  ","X   OXO X","X   OXOOX","X   OXOX ","X   OXOXO",
"X   OXX O","X   OXXO ","X   OXXOO","X   X   O","X   X  O ","X   X  OO","X   X O  ","X   X O O",
"X   X OO ","X   X OOX","X   X OXO","X   X XOO","X   XO   ","X   XO  O","X   XO O ","X   XO OX",
"X   XO XO","X   XOO  ","X   XOO X","X   XOOX ","X   XOOXO","X   XOX O","X   XOXO ","X   XOXOO",
"X   XX OO","X   XXO O","X   XXOO ","X   XXOOO","X  O     ","X  O    X","X  O   OX","X  O   X ",
"X  O   XO","X  O  O X","X  O  OX ","X  O  OXX","X  O  X  ","X  O  X O","X  O  XO ","X  O  XOX",
"X  O  XXO","X  O O  X","X  O O X ","X  O O XX","X  O OOXX","X  O OX  ","X  O OX X","X  O OXOX",
"X  O OXX ","X  O OXXO","X  O X   ","X  O X  O","X  O X O ","X  O X OX","X  O X XO","X  O XO  ",
"X  O XO X","X  O XOOX","X  O XOX ","X  O XOXO","X  O XX O","X  O XXO ","X  O XXOO","X  OO   X",
"X  OO  X ","X  OO  XX","X  OO OXX","X  OO X  ","X  OO X X","X  OO XOX","X  OO XX ","X  OO XXO",
"X  OOO XX","X  OOOX X","X  OOOXX ","X  OOX   ","X  OOX  X","X  OOX OX","X  OOX X ","X  OOX XO",
"X  OOXO X","X  OOXOX ","X  OOXOXX","X  OOXX  ","X  OOXX O","X  OOXXO ","X  OOXXOX","X  OOXXXO",
"X  OX    ","X  OX   O","X  OX  O ","X  OX  OX","X  OX  XO","X  OX O  ","X  OX O X","X  OX OX ",
"X  OX OXO","X  OX X O","X  OX XO ","X  OX XOO","X  OXO   ","X  OXO  X","X  OXO X ","X  OXO XO",
"X  OXOOX ","X  OXOOXX","X  OXOX  ","X  OXOX O","X  OXOXO ","X  OXOXOX","X  OXOXXO","X  OXX  O",
"X  OXX O ","X  OXX OO","X  OXXO  ","X  OXXO O","X  OXXOO ","X  OXXOOX","X  OXXOXO","X  OXXXOO",
"X  X    O","X  X   O ","X  X   OO","X  X  O  ","X  X  O O","X  X  OO ","X  X  OOX","X  X  OXO",
"X  X  XOO","X  X O   ","X  X O  O","X  X O O ","X  X O OX","X  X O XO","X  X OO  ","X  X OO X",
"X  X OOOX","X  X OOX ","X  X OOXO","X  X OX O","X  X OXO ","X  X X OO","X  X XO O","X  X XOO ",
"X  X XOOO","X  XO    ","X  XO   O","X  XO  O ","X  XO  OX","X  XO  XO","X  XO O  ","X  XO O X",
"X  XO OOX","X  XO OX ","X  XO OXO","X  XO X O","X  XO XO ","X  XOO   ","X  XOO  X","X  XOO OX",
"X  XOO X ","X  XOO XO","X  XOOO X","X  XOOOX ","X  XOOOXX","X  XOOX  ","X  XOOXOX","X  XOOXXO",
"X  XOX  O","X  XOX O ","X  XOX OO","X  XOXO  ","X  XOXO O","X  XOXOO ","X  XOXOOX","X  XOXOXO",
"X  XOXXOO","X  XX  OO","X  XX O O","X  XX OO ","X  XX OOO","X  XXO  O","X  XXO O ","X  XXO OO",
"X  XXOO  ","X  XXOO O","X  XXOOO ","X  XXOOOX","X  XXOOXO","X  XXOXOO","X O      ","X O     X",
"X O    OX","X O    X ","X O    XO","X O   O X","X O   OX ","X O   OXX","X O   X  ","X O   X O",
"X O   XO ","X O   XOX","X O   XXO","X O  O  X","X O  O X ","X O  O XX","X O  OOXX","X O  OX  ",
"X O  OX X","X O  OXOX","X O  OXX ","X O  OXXO","X O  X   ","X O  X  O","X O  X O ","X O  X OX",
"X O  X XO","X O  XO  ","X O  XO X","X O  XOOX","X O  XOX ","X O  XOXO","X O  XX O","X O  XXO ",
"X O  XXOO","X O O   X","X O O  X ","X O O  XX","X O O OXX","X O O X  ","X O O X X","X O O XOX",
"X O O XX ","X O O XXO","X O OO XX","X O OOX X","X O OOXX ","X O OOXXX","X O OX   ","X O OX  X",
"X O OX OX","X O OX X ","X O OX XO","X O OXO X","X O OXOX ","X O OXX  ","X O OXX O","X O OXXO ",
"X O OXXOX","X O OXXXO","X O X    ","X O X   O","X O X  O ","X O X  OX","X O X  XO","X O X O  ",
"X O X O X","X O X OX ","X O X OXO","X O X X O","X O X XO ","X O X XOO","X O XO   ","X O XO  X",
"X O XO X ","X O XO XO","X O XOOX ","X O XOOXX","X O XOX  ","X O XOX O","X O XOXO ","X O XOXOX",
"X O XX  O","X O XX O ","X O XX OO","X O XXO  ","X O XXO O","X O XXOO ","X O XXOOX","X O XXOXO",
"X O XXXOO","X OO    X","X OO   X ","X OO   XX","X OO  OXX","X OO  X  ","X OO  X X","X OO  XOX",
"X OO  XX ","X OO  XXO","X OO O XX","X OO OX X","X OO OXX ","X OO OXXX","X OO X   ","X OO X  X",
"X OO X OX","X OO X X ","X OO X XO","X OO XO X","X OO XOX ","X OO XOXX","X OO XX  ","X OO XX O",
"X OO XXO ","X OO XXOX","X OO XXXO","X OOO  XX","X OOO X X","X OOO XX ","X OOO XXX","X OOOX  X",
"X OOOX X ","X OOOX XX","X OOOXOXX","X OOOXX  ","X OOOXX X","X OOOXXOX","X OOOXXX ","X OOOXXXO",
"X OOX    ","X OOX   X","X OOX  X ","X OOX  XO","X OOX OX ","X OOX OXX","X OOX X  ","X OOX X O",
"X OOX XO ","X OOX XOX","X OOX XXO","X OOXO X ","X OOXO XX","X OOXOX  ","X OOXOX X","X OOXOXX ",
"X OOXOXXO","X OOXX   ","X OOXX  O","X OOXX O ","X OOXX OX","X OOXX XO","X OOXXO  ","X OOXXO X",
"X OOXXOX ","X OOXXOXO","X OOXXX O","X OOXXXO ","X OOXXXOO","X OX     ","X OX    O","X OX   O ",
"X OX   OX","X OX   XO","X OX  O  ","X OX  O X","X OX  OOX","X OX  OX ","X OX  OXO","X OX  X O",
"X OX  XO ","X OX O   ","X OX O  X","X OX O OX","X OX O X ","X OX O XO","X OX OO X","X OX OOX ",
"X OX OOXX","X OX OX  ","X OX OXOX","X OX X  O","X OX X O ","X OX X OO","X OX XO  ","X OX XO O",
"X OX XOO ","X OX XOOX","X OX XOXO","X OX XXOO","X OXO    ","X OXO   X","X OXO  OX","X OXO  X ",
"X OXO  XO","X OXO O X","X OXO OX ","X OXO X  ","X OXO XOX","X OXO XXO","X OXOO  X","X OXOO X ",
"X OXOO XX","X OXOOOXX","X OXOOX X","X OXOOXX ","X OXOX   ","X OXOX  O","X OXOX O ","X OXOX OX",
"X OXOX XO","X OXOXO  ","X OXOXOOX","X OXOXOXO","X OXOXX O","X OXOXXO ","X OXX   O","X OXX  O ",
"X OXX  OO","X OXX O  ","X OXX O O","X OXX OO ","X OXX OOX","X OXX OXO","X OXX XOO","X OXXO   ",
"X OXXO  O","X OXXO O ","X OXXO OX","X OXXOO  ","X OXXOO X","X OXXOOX ","X OXXOOXO","X OXXOXO ",
"X OXXX OO","X OXXXO O","X OXXXOO ","X X     O","X X    O ","X X    OO","X X   O  ","X X   O O",
"X X   OO ","X X   OOX","X X   OXO","X X   XOO","X X  O   ","X X  O  O","X X  O O ","X X  O OX",
"X X  O XO","X X  OO  ","X X  OO X","X X  OOOX","X X  OOX ","X X  OOXO","X X  OX O","X X  OXO ",
"X X  OXOO","X X  X OO","X X  XO O","X X  XOO ","X X  XOOO","X X O    ","X X O   O","X X O  O ",
"X X O  OX","X X O  XO","X X O O  ","X X O O X","X X O OOX","X X O OX ","X X O OXO","X X O X O",
"X X O XO ","X X O XOO","X X OO   ","X X OO  X","X X OO OX","X X OO X ","X X OO XO","X X OOO X",
"X X OOOX ","X X OOOXX","X X OOX  ","X X OOX O","X X OOXO ","X X OOXOX","X X OOXXO","X X OX  O",
"X X OX O ","X X OX OO","X X OXO  ","X X OXO O","X X OXOO ","X X OXOOX","X X OXOXO","X X OXXOO",
"X X X  OO","X X X O O","X X X OO ","X X X OOO","X X XO  O","X X XO O ","X X XO OO","X X XOO  ",
"X X XOO O","X X XOOO ","X X XOOOX","X X XOOXO","X X XOXOO","X XO     ","X XO    O","X XO   O ",
"X XO   OX","X XO   XO","X XO  O  ","X XO  O X","X XO  OOX","X XO  OX ","X XO  OXO","X XO  X O",
"X XO  XO ","X XO  XOO","X XO O   ","X XO O  X","X XO O OX","X XO O X ","X XO O XO","X XO OO X",
"X XO OOX ","X XO OOXX","X XO OX  ","X XO OX O","X XO OXO ","X XO OXOX","X XO OXXO","X XO X  O",
"X XO X O ","X XO X OO","X XO XO  ","X XO XO O","X XO XOO ","X XO XOOX","X XO XOXO","X XO XXOO",
"X XOO    ","X XOO   X","X XOO  OX","X XOO  X ","X XOO  XO","X XOO O X","X XOO OX ","X XOO OXX",
"X XOO X  ","X XOO X O","X XOO XO ","X XOO XOX","X XOO XXO","X XOOO  X","X XOOO X ","X XOOOOXX",
"X XOOOX  ","X XOOOXOX","X XOOOXXO","X XOOX   ","X XOOX  O","X XOOX O ","X XOOX OX","X XOOX XO",
"X XOOXO  ","X XOOXO X","X XOOXOX ","X XOOXOXO","X XOOXX O","X XOOXXO ","X XOOXXOO","X XOX   O",
"X XOX  O ","X XOX  OO","X XOX O  ","X XOX O O","X XOX OO ","X XOX OOX","X XOX OXO","X XOX XOO",
"X XOXO   ","X XOXO  O","X XOXO O ","X XOXO OX","X XOXO XO","X XOXOO  ","X XOXOO X","X XOXOOX ",
"X XOXOOXO","X XOXOX O","X XOXOXO ","X XOXX OO","X XOXXO O","X XOXXOO ","X XOXXOOO","X XX   OO",
"X XX  O O","X XX  OO ","X XX  OOO","X XX O  O","X XX O O ","X XX O OO","X XX OO  ","X XX OO O",
"X XX OOO ","X XX OOOX","X XX OOXO","X XX OXOO","X XXO   O","X XXO  O ","X XXO  OO","X XXO O  ",
"X XXO O O","X XXO OO ","X XXO OOX","X XXO OXO","X XXO XOO","X XXOO   ","X XXOO  O","X XXOO O ",
"X XXOO OX","X XXOO XO","X XXOOO  ","X XXOOO X","X XXOOOOX","X XXOOOX ","X XXOOOXO","X XXOOX O",
"X XXOOXO ","X XXOX OO","X XXOXO O","X XXOXOO ","X XXOXOOO","X XXXO OO","X XXXOO O","X XXXOOO ",
"X XXXOOOO","XO       ","XO      X","XO     OX","XO     X ","XO     XO","XO    O X","XO    OX ",
"XO    OXX","XO    X  ","XO    X O","XO    XO ","XO    XOX","XO    XXO","XO   O  X","XO   O X ",
"XO   O XX","XO   OOXX","XO   OX  ","XO   OX X","XO   OXOX","XO   OXX ","XO   OXXO","XO   X   ",
"XO   X  O","XO   X O ","XO   X OX","XO   X XO","XO   XO  ","XO   XO X","XO   XOOX","XO   XOX ",
"XO   XOXO","XO   XX O","XO   XXO ","XO   XXOO","XO  O   X","XO  O  X ","XO  O  XX","XO  O OXX",
"XO  O X  ","XO  O X X","XO  O XOX","XO  O XX ","XO  O XXO","XO  OO XX","XO  OOX X","XO  OOXX ",
"XO  OOXXX","XO  OX   ","XO  OX  X","XO  OX OX","XO  OX X ","XO  OX XO","XO  OXO X","XO  OXOX ",
"XO  OXOXX","XO  OXX  ","XO  OXX O","XO  OXXO ","XO  OXXXO","XO  X    ","XO  X   O","XO  X  O ",
"XO  X  OX","XO  X  XO","XO  X O  ","XO  X O X","XO  X OX ","XO  X OXO","XO  X X O","XO  X XO ",
"XO  X XOO","XO  XO   ","XO  XO  X","XO  XO X ","XO  XO XO","XO  XOOX ","XO  XOOXX","XO  XOX  ",
"XO  XOX O","XO  XOXO ","XO  XOXOX","XO  XOXXO","XO  XX  O","XO  XX O ","XO  XX OO","XO  XXO  ",
"XO  XXO O","XO  XXOO ","XO  XXOOX","XO  XXOXO","XO  XXXOO","XO O    X","XO O   X ","XO O   XX",
"XO O  OXX","XO O  X  ","XO O  X X","XO O  XOX","XO O  XX ","XO O  XXO","XO O O XX","XO O OX X",
"XO O OXX ","XO O OXXX","XO O X   ","XO O X  X","XO O X OX","XO O X X ","XO O X XO","XO O XO X",
"XO O XOX ","XO O XOXX","XO O XX  ","XO O XX O","XO O XXO ","XO O XXOX","XO O XXXO","XO OO  XX",
"XO OO X X","XO OO XX ","XO OO XXX","XO OOX  X","XO OOX X ","XO OOX XX","XO OOXOXX","XO OOXX  ",
"XO OOXX X","XO OOXXOX","XO OOXXX ","XO OOXXXO","XO OX    ","XO OX   X","XO OX  X ","XO OX  XO",
"XO OX OX ","XO OX OXX","XO OX X  ","XO OX X O","XO OX XO ","XO OX XOX","XO OX XXO","XO OXO X ",
"XO OXO XX","XO OXOX  ","XO OXOX X","XO OXOXX ","XO OXOXXO","XO OXX   ","XO OXX  O","XO OXX O ",
"XO OXX OX","XO OXX XO","XO OXXO  ","XO OXXO X","XO OXXOX ","XO OXXOXO","XO OXXX O","XO OXXXO ",
"XO OXXXOO","XO X     ","XO X    O","XO X   O ","XO X   OX","XO X   XO","XO X  O  ","XO X  O X",
"XO X  OOX","XO X  OX ","XO X  OXO","XO X  X O","XO X  XO ","XO X O   ","XO X O  X","XO X O OX",
"XO X O X ","XO X O XO","XO X OO X","XO X OOX ","XO X OOXX","XO X OX  ","XO X OXOX","XO X OXXO",
"XO X X  O","XO X X O ","XO X X OO","XO X XO  ","XO X XO O","XO X XOO ","XO X XOOX","XO X XOXO",
"XO X XXOO","XO XO    ","XO XO   X","XO XO  OX","XO XO  X ","XO XO  XO","XO XO O X","XO XO OX ",
"XO XO OXX","XO XO X  ","XO XO XXO","XO XOO  X","XO XOO X ","XO XOO XX","XO XOOOXX","XO XOOX X",
"XO XOOXX ","XO XOX   ","XO XOX  O","XO XOX O ","XO XOX XO","XO XOXO  ","XO XOXO X","XO XOXOOX",
"XO XOXOX ","XO XOXOXO","XO XOXX O","XO XX   O","XO XX  O ","XO XX  OO","XO XX O  ","XO XX O O",
"XO XX OO ","XO XX OOX","XO XX OXO","XO XX XOO","XO XXO   ","XO XXO  O","XO XXO O ","XO XXO OX",
"XO XXO XO","XO XXOO  ","XO XXOO X","XO XXOOX ","XO XXOOXO","XO XXOX O","XO XXOXO ","XO XXX OO",
"XO XXXO O","XO XXXOO ","XOO     X","XOO    X ","XOO    XX","XOO   OXX","XOO   X  ","XOO   X X",
"XOO   XOX","XOO   XX ","XOO   XXO","XOO  O XX","XOO  OX X","XOO  OXX ","XOO  OXXX","XOO  X   ",
"XOO  X  X","XOO  X OX","XOO  X X ","XOO  X XO","XOO  XO X","XOO  XOX ","XOO  XOXX","XOO  XX  ",
"XOO  XX O","XOO  XXO ","XOO  XXOX","XOO  XXXO","XOO O  XX","XOO O X X","XOO O XX ","XOO O XXX",
"XOO OX  X","XOO OX X ","XOO OX XX","XOO OXOXX","XOO OXX  ","XOO OXX X","XOO OXXOX","XOO OXXX ",
"XOO OXXXO","XOO X    ","XOO X   X","XOO X  X ","XOO X  XO","XOO X OX ","XOO X OXX","XOO X X  ",
"XOO X X O","XOO X XO ","XOO X XOX","XOO X XXO","XOO XO X ","XOO XO XX","XOO XOX  ","XOO XOX X",
"XOO XOXX ","XOO XOXXO","XOO XX   ","XOO XX  O","XOO XX O ","XOO XX OX","XOO XX XO","XOO XXO  ",
"XOO XXO X","XOO XXOX ","XOO XXOXO","XOO XXX O","XOO XXXO ","XOO XXXOO","XOOO   XX","XOOO  X X",
"XOOO  XX ","XOOO  XXX","XOOO X  X","XOOO X X ","XOOO X XX","XOOO XOXX","XOOO XX  ","XOOO XX X",
"XOOO XXOX","XOOO XXX ","XOOO XXXO","XOOOOX XX","XOOOOXX X","XOOOOXXX ","XOOOOXXXX","XOOOX  X ",
"XOOOX  XX","XOOOX X  ","XOOOX X X","XOOOX XX ","XOOOX XXO","XOOOXOXX ","XOOOXOXXX","XOOOXX   ",
"XOOOXX  X","XOOOXX X ","XOOOXX XO","XOOOXXOX ","XOOOXXOXX","XOOOXXX  ","XOOOXXX O","XOOOXXXO ",
"XOOOXXXOX","XOOOXXXXO","XOOX     ","XOOX    X","XOOX   OX","XOOX   X ","XOOX   XO","XOOX  O X",
"XOOX  OX ","XOOX  OXX","XOOX  X  ","XOOX  XOX","XOOX  XXO","XOOX O  X","XOOX O X ","XOOX O XX",
"XOOX OOXX","XOOX OX X","XOOX OXX ","XOOX X   ","XOOX X  O","XOOX X O ","XOOX X OX","XOOX X XO",
"XOOX XO  ","XOOX XO X","XOOX XOOX","XOOX XOX ","XOOX XOXO","XOOX XX O","XOOX XXO ","XOOXO   X",
"XOOXO  X ","XOOXO  XX","XOOXO OXX","XOOXO X X","XOOXO XX ","XOOXOO XX","XOOXOOXXX","XOOXOX   ",
"XOOXOX  X","XOOXOX OX","XOOXOX X ","XOOXOX XO","XOOXOXO X","XOOXOXOX ","XOOXOXX  ","XOOXOXXXO",
"XOOXX    ","XOOXX   O","XOOXX  O ","XOOXX  OX","XOOXX  XO","XOOXX O  ","XOOXX O X","XOOXX OX ",
"XOOXX OXO","XOOXX X O","XOOXX XO ","XOOXXO   ","XOOXXO  X","XOOXXO X ","XOOXXO XO","XOOXXOOX ",
"XOOXXOOXX","XOOXXOX  ","XOOXXOXOX","XOOXXX  O","XOOXXX O ","XOOXXXO  ","XOOXXXOOX","XOOXXXOXO",
"XOOXXXXOO","XOX      ","XOX     O","XOX    O ","XOX    OX","XOX    XO","XOX   O  ","XOX   O X",
"XOX   OOX","XOX   OX ","XOX   OXO","XOX   X O","XOX   XO ","XOX   XOO","XOX  O   ","XOX  O  X",
"XOX  O OX","XOX  O X ","XOX  O XO","XOX  OO X","XOX  OOX ","XOX  OOXX","XOX  OX  ","XOX  OX O",
"XOX  OXO ","XOX  OXOX","XOX  OXXO","XOX  X  O","XOX  X O ","XOX  X OO","XOX  XO  ","XOX  XO O",
"XOX  XOO ","XOX  XOOX","XOX  XOXO","XOX  XXOO","XOX O    ","XOX O   X","XOX O  OX","XOX O  X ",
"XOX O  XO","XOX O O X","XOX O OX ","XOX O OXX","XOX O X  ","XOX O X O","XOX O XO ","XOX O XXO",
"XOX OO  X","XOX OO X ","XOX OO XX","XOX OOOXX","XOX OOX  ","XOX OOX X","XOX OOXOX","XOX OOXX ",
"XOX OOXXO","XOX OX   ","XOX OX  O","XOX OX O ","XOX OX XO","XOX OXO  ","XOX OXO X","XOX OXOX ",
"XOX OXOXO","XOX OXX O","XOX OXXOO","XOX X   O","XOX X  O ","XOX X  OO","XOX X O  ","XOX X O O",
"XOX X OO ","XOX X OOX","XOX X OXO","XOX X XOO","XOX XO   ","XOX XO  O","XOX XO O ","XOX XO OX",
"XOX XO XO","XOX XOO  ","XOX XOO X","XOX XOOX ","XOX XOOXO","XOX XOX O","XOX XOXO ","XOX XX OO",
"XOX XXO O","XOX XXOO ","XOX XXOOO","XOXO     ","XOXO    X","XOXO   OX","XOXO   X ","XOXO   XO",
"XOXO  O X","XOXO  OX ","XOXO  OXX","XOXO  X  ","XOXO  X O","XOXO  XO ","XOXO  XOX","XOXO  XXO",
"XOXO O  X","XOXO O X ","XOXO O XX","XOXO OOXX","XOXO OX  ","XOXO OX X","XOXO OXOX","XOXO OXX ",
"XOXO OXXO","XOXO X   ","XOXO X  O","XOXO X O ","XOXO X OX","XOXO X XO","XOXO XO  ","XOXO XO X",
"XOXO XOX ","XOXO XOXO","XOXO XX O","XOXO XXO ","XOXO XXOO","XOXOO   X","XOXOO  X ","XOXOO  XX",
"XOXOO OXX","XOXOO X  ","XOXOO X X","XOXOO XOX","XOXOO XX ","XOXOO XXO","XOXOOO XX","XOXOOOX X",
"XOXOOOXX ","XOXOOX   ","XOXOOX  X","XOXOOX X ","XOXOOX XO","XOXOOXOX ","XOXOOXOXX","XOXOOXX  ",
"XOXOOXX O","XOXOOXXO ","XOXOOXXXO","XOXOX    ","XOXOX   O","XOXOX  O ","XOXOX  OX","XOXOX  XO",
"XOXOX O  ","XOXOX O X","XOXOX OX ","XOXOX OXO","XOXOX X O","XOXOX XO ","XOXOXO   ","XOXOXO  X",
"XOXOXO X ","XOXOXO XO","XOXOXOOX ","XOXOXOOXX","XOXOXOX  ","XOXOXOXOX","XOXOXOXXO","XOXOXX  O",
"XOXOXX O ","XOXOXX OO","XOXOXXO  ","XOXOXXO O","XOXOXXOO ","XOXOXXOOX","XOXOXXOXO","XOXOXXXOO",
"XOXX    O","XOXX   O ","XOXX   OO","XOXX  O  ","XOXX  O O","XOXX  OO ","XOXX  OOX","XOXX  OXO",
"XOXX  XOO","XOXX O   ","XOXX O  O","XOXX O O ","XOXX O OX","XOXX O XO","XOXX OO  ","XOXX OO X",
"XOXX OOOX","XOXX OOX ","XOXX OOXO","XOXX OX O","XOXX OXO ","XOXX X OO","XOXX XO O","XOXX XOO ",
"XOXX XOOO","XOXXO    ","XOXXO   O","XOXXO  O ","XOXXO  XO","XOXXO O  ","XOXXO O X","XOXXO OOX",
"XOXXO OX ","XOXXO OXO","XOXXO X O","XOXXOO   ","XOXXOO  X","XOXXOO OX","XOXXOO X ","XOXXOO XO",
"XOXXOOO X","XOXXOOOX ","XOXXOOOXX","XOXXOOX  ","XOXXOOXXO","XOXXOX  O","XOXXOX OO","XOXXOXO  ",
"XOXXOXO O","XOXXOXOO ","XOXXOXOXO","XOXXX  OO","XOXXX O O","XOXXX OO ","XOXXX OOO","XOXXXO  O",
"XOXXXO O ","XOXXXO OO","XOXXXOO  ","XOXXXOO O","XOXXXOOO ","XOXXXOOOX","XOXXXOOXO","XOXXXOXOO",
"XX      O","XX     O ","XX     OO","XX    O  ","XX    O O","XX    OO ","XX    OOX","XX    OXO",
"XX    XOO","XX   O   ","XX   O  O","XX   O O ","XX   O OX","XX   O XO","XX   OO  ","XX   OO X",
"XX   OOOX","XX   OOX ","XX   OOXO","XX   OX O","XX   OXO ","XX   OXOO","XX   X OO","XX   XO O",
"XX   XOO ","XX   XOOO","XX  O    ","XX  O   O","XX  O  O ","XX  O  OX","XX  O  XO","XX  O O  ",
"XX  O O X","XX  O OOX","XX  O OX ","XX  O OXO","XX  O X O","XX  O XO ","XX  O XOO","XX  OO   ",
"XX  OO  X","XX  OO OX","XX  OO X ","XX  OO XO","XX  OOO X","XX  OOOX ","XX  OOOXX","XX  OOX  ",
"XX  OOX O","XX  OOXO ","XX  OOXOX","XX  OOXXO","XX  OX  O","XX  OX O ","XX  OX OO","XX  OXO  ",
"XX  OXO O","XX  OXOO ","XX  OXOOX","XX  OXOXO","XX  OXXOO","XX  X  OO","XX  X O O","XX  X OO ",
"XX  X OOO","XX  XO  O","XX  XO O ","XX  XO OO","XX  XOO  ","XX  XOO O","XX  XOOO ","XX  XOOOX",
"XX  XOOXO","XX  XOXOO","XX O     ","XX O    O","XX O   O ","XX O   OX","XX O   XO","XX O  O  ",
"XX O  O X","XX O  OOX","XX O  OX ","XX O  OXO","XX O  X O","XX O  XO ","XX O  XOO","XX O O   ",
"XX O O  X","XX O O OX","XX O O X ","XX O O XO","XX O OO X","XX O OOX ","XX O OOXX","XX O OX  ",
"XX O OX O","XX O OXO ","XX O OXOX","XX O OXXO","XX O X  O","XX O X O ","XX O X OO","XX O XO  ",
"XX O XO O","XX O XOO ","XX O XOOX","XX O XOXO","XX O XXOO","XX OO    ","XX OO   X","XX OO  OX",
"XX OO  X ","XX OO  XO","XX OO O X","XX OO OX ","XX OO OXX","XX OO X  ","XX OO X O","XX OO XO ",
"XX OO XOX","XX OO XXO","XX OOO  X","XX OOO X ","XX OOOOXX","XX OOOX  ","XX OOOXOX","XX OOOXXO",
"XX OOX   ","XX OOX  O","XX OOX O ","XX OOX OX","XX OOX XO","XX OOXO  ","XX OOXO X","XX OOXOOX",
"XX OOXOX ","XX OOXOXO","XX OOXX O","XX OOXXO ","XX OOXXOO","XX OX   O","XX OX  O ","XX OX  OO",
"XX OX O  ","XX OX O O","XX OX OO ","XX OX OOX","XX OX OXO","XX OX XOO","XX OXO   ","XX OXO  O",
"XX OXO O ","XX OXO OX","XX OXO XO","XX OXOO  ","XX OXOO X","XX OXOOX ","XX OXOX O","XX OXOXO ",
"XX OXOXOO","XX OXX OO","XX OXXO O","XX OXXOO ","XX OXXOOO","XX X   OO","XX X  O O","XX X  OO ",
"XX X  OOO","XX X O  O","XX X O O ","XX X O OO","XX X OO  ","XX X OO O","XX X OOO ","XX X OOOX",
"XX X OOXO","XX X OXOO","XX XO   O","XX XO  O ","XX XO  OO","XX XO O  ","XX XO O O","XX XO OO ",
"XX XO OOX","XX XO OXO","XX XO XOO","XX XOO   ","XX XOO  O","XX XOO O ","XX XOO OX","XX XOO XO",
"XX XOOO  ","XX XOOO X","XX XOOOOX","XX XOOOX ","XX XOOOXO","XX XOOX O","XX XOOXO ","XX XOX OO",
"XX XOXO O","XX XOXOO ","XX XOXOOO","XX XXO OO","XX XXOO O","XX XXOOO ","XX XXOOOO","XXO      ",
"XXO     O","XXO    O ","XXO    OX","XXO    XO","XXO   O  ","XXO   O X","XXO   OOX","XXO   OX ",
"XXO   OXO","XXO   X O","XXO   XO ","XXO   XOO","XXO  O   ","XXO  O  X","XXO  O OX","XXO  O X ",
"XXO  O XO","XXO  OO X","XXO  OOX ","XXO  OOXX","XXO  OX  ","XXO  OX O","XXO  OXO ","XXO  OXOX",
"XXO  X  O","XXO  X O ","XXO  X OO","XXO  XO  ","XXO  XO O","XXO  XOO ","XXO  XOOX","XXO  XOXO",
"XXO  XXOO","XXO O    ","XXO O   X","XXO O  OX","XXO O  X ","XXO O  XO","XXO O O X","XXO O OX ",
"XXO O X  ","XXO O X O","XXO O XO ","XXO O XOX","XXO O XXO","XXO OO  X","XXO OO X ","XXO OO XX",
"XXO OOOXX","XXO OOX  ","XXO OOX X","XXO OOXOX","XXO OOXX ","XXO OOXXO","XXO OX   ","XXO OX  O",
"XXO OX O ","XXO OX OX","XXO OX XO","XXO OXO  ","XXO OXOOX","XXO OXOXO","XXO OXX O","XXO OXXO ",
"XXO OXXOO","XXO X   O","XXO X  O ","XXO X  OO","XXO X O  ","XXO X O O","XXO X OO ","XXO X OOX",
"XXO X OXO","XXO X XOO","XXO XO   ","XXO XO  O","XXO XO O ","XXO XO OX","XXO XOO  ","XXO XOO X",
"XXO XOOX ","XXO XOXO ","XXO XOXOO","XXO XX OO","XXO XXO O","XXO XXOO ","XXO XXOOO","XXOO     ",
"XXOO    X","XXOO   OX","XXOO   X ","XXOO   XO","XXOO  O X","XXOO  OX ","XXOO  OXX","XXOO  X  ",
"XXOO  X O","XXOO  XO ","XXOO  XOX","XXOO  XXO","XXOO O  X","XXOO O X ","XXOO O XX","XXOO OOXX",
"XXOO OX  ","XXOO OX X","XXOO OXOX","XXOO OXX ","XXOO OXXO","XXOO X   ","XXOO X  O","XXOO X O ",
"XXOO X OX","XXOO X XO","XXOO XO  ","XXOO XO X","XXOO XOOX","XXOO XOX ","XXOO XOXO","XXOO XX O",
"XXOO XXO ","XXOO XXOO","XXOOO   X","XXOOO  X ","XXOOO  XX","XXOOO OXX","XXOOO X  ","XXOOO X X",
"XXOOO XOX","XXOOO XX ","XXOOO XXO","XXOOOO XX","XXOOOOX X","XXOOOOXX ","XXOOOX   ","XXOOOX  X",
"XXOOOX OX","XXOOOX X ","XXOOOX XO","XXOOOXO X","XXOOOXOX ","XXOOOXX  ","XXOOOXX O","XXOOOXXO ",
"XXOOOXXOX","XXOOOXXXO","XXOOX    ","XXOOX   O","XXOOX  O ","XXOOX  OX","XXOOX  XO","XXOOX O  ",
"XXOOX O X","XXOOX OX ","XXOOX X O","XXOOX XO ","XXOOX XOO","XXOOXO   ","XXOOXO  X","XXOOXO X ",
"XXOOXOOXX","XXOOXOX  ","XXOOXOX O","XXOOXOXO ","XXOOXOXOX","XXOOXX  O","XXOOXX O ","XXOOXX OO",
"XXOOXXO  ","XXOOXXO O","XXOOXXOO ","XXOOXXOOX","XXOOXXOXO","XXOOXXXOO","XXOX    O","XXOX   O ",
"XXOX   OO","XXOX  O  ","XXOX  O O","XXOX  OO ","XXOX  OOX","XXOX  OXO","XXOX  XOO","XXOX O   ",
"XXOX O  O","XXOX O O ","XXOX O OX","XXOX OO  ","XXOX OO X","XXOX OOOX","XXOX OOX ","XXOX OOXO",
"XXOX OXO ","XXOX X OO","XXOX XO O","XXOX XOO ","XXOX XOOO","XXOXO    ","XXOXO   O","XXOXO  O ",
"XXOXO  OX","XXOXO  XO","XXOXO O  ","XXOXO OOX","XXOXO OXO","XXOXO X O","XXOXO XO ","XXOXOO   ",
"XXOXOO  X","XXOXOO OX","XXOXOO X ","XXOXOO XO","XXOXOOO X","XXOXOOOX ","XXOXOOX  ","XXOXOOXOX",
"XXOXOX  O","XXOXOX O ","XXOXOX OO","XXOXOXO O","XXOXOXOO ","XXOXOXXOO","XXOXX  OO","XXOXX O O",
"XXOXX OO ","XXOXX OOO","XXOXXO O ","XXOXXO OO","XXOXXOO  ","XXOXXOO O","XXOXXOOO ","XXOXXOOOX",
"XXX    OO","XXX   O O","XXX   OO ","XXX  O  O","XXX  O O ","XXX  OO  ","XXX  OOOX","XXX  OOXO",
"XXX  OXOO","XXX O   O","XXX O  O ","XXX O O  ","XXX O OOX","XXX O OXO","XXX O XOO","XXX OO   ",
"XXX OO OX","XXX OO XO","XXX OOO X","XXX OOOX ","XXX OOX O","XXX OOXO ","XXX OX OO","XXX OXO O",
"XXX OXOO ","XXX XO OO","XXX XOO O","XXX XOOO ","XXXO    O","XXXO   O ","XXXO  O  ","XXXO  OOX",
"XXXO  OXO","XXXO  XOO","XXXO O   ","XXXO O OX","XXXO O XO","XXXO OO X","XXXO OOX ","XXXO OX O",
"XXXO OXO ","XXXO X OO","XXXO XO O","XXXO XOO ","XXXOO    ","XXXOO  OX","XXXOO  XO","XXXOO O X",
"XXXOO OX ","XXXOO X O","XXXOO XO ","XXXOOX  O","XXXOOX O ","XXXOOXO  ","XXXOOXOOX","XXXOOXOXO",
"XXXOOXXOO","XXXOX  OO","XXXOX O O","XXXOX OO ","XXXOXO  O","XXXOXO O ","XXXOXOO  ","XXXOXOOOX",
"XXXOXOOXO","XXXOXOXOO","XXXX O OO","XXXX OO O","XXXX OOO ","XXXXO  OO","XXXXO O O","XXXXO OO ",
"XXXXOO  O","XXXXOO O ","XXXXOOO  ","XXXXOOOOX","XXXXOOOXO","XXXXOOXOO"
}; // 5478 possible states

class Solution {
public:
    bool validTicTacToe(vector<string>& board) {
        return states. find( board[0] + board[1] + board[2]) != states. end();
    }
};

TEST_CASE("table", "[validTicTacToe]") {
    Solution s;
    vector<string> b1{"O  ","   ","   "},
                   b2{"XOX"," X ","   "},
                   b3{"XXX","   ","OOO"},
                   b4{"XOX","O O","XOX"},
                   b5{"XXX","XOO","XOO"};
    CHECK( s. validTicTacToe( b1) == false);
    CHECK( s. validTicTacToe( b2) == false);
    CHECK( s. validTicTacToe( b3) == false);
    CHECK( s. validTicTacToe( b4) == true);
    CHECK( s. validTicTacToe( b5) == true);
}
